### ISSUE TITLE
sleep() doesn't work right.

### ISSUE THREAD

**Issue by SoniEx2** [dan200/ComputerCraft#10]
http://www.computercraft.info/forums2/index.php?/topic/22861-1710-sleep-sleeping-for-incorrect-amount-of-ticks/

A workaround is to call sleep(0.05) in a loop:

```lua
function fixsleep(n)
  sleep(n % 0.05) -- at least a 1-tick sleep
  for i=2,math.floor(n * 20) do
    sleep(0.05)
  end
end
```

**Comment by dan200** [comment]
fixed
