### ISSUE TITLE
Non-existant function turtle.inspectSlot in turtle's help document

### ISSUE THREAD

**Issue by KingofGamesYami** [dan200/ComputerCraft#102]
turtle.inspectSlot is not a function, yet it is listed as one in the help file.

[The line in question](https://github.com/alekso56/ComputercraftLua/blob/master/rom/help/turtle#L34)

[CC Forum Post that discovered this](http://www.computercraft.info/forums2/index.php?/topic/26573-turtleinspectslot-slotnum-missing/)

**Comment by dan200** [comment]
Fixed for next release
