### ISSUE TITLE
[CCv1.8.9][SSP/SMP] Turtle Inventory GUI missing slots

### ISSUE THREAD

**Issue by exoskeleton500** [dan200/ComputerCraft#104]
When right-clicking a Turtle in Spectator Mode (gamemode 3) the inventory GUI that pops up has only the first 9 slots, not the full 16.

https://imgur.com/a/s3elO

**Comment by KnightMiner** [comment]
Duplicate of #53.

**Comment by dan200** [comment]
Yep. Also not high priority at all.
