### ISSUE TITLE
Certain computer craft items recipes can't be viewed via r key in nei

### ISSUE THREAD

**Issue by 31trainman** [dan200/ComputerCraft#106]
I'm noticing some of your mods items/blocks registered in preint phase I'm noticing that upon looking at the various colored floppy disk recipes it only shows the blue one in nei  http://pastebin.com/UHGcWZxH

Latest computer craft for 1.7.10
Mod list: http://pastebin.com/ss7RbZ2k
Forge 1614 mc 1.7.10
Java 8 update 91
Mac os x 10.11.4

**Comment by lurquhar1221** [comment]
This is a problem with NEI, not computercraft.

**Comment by 31trainman** [comment]
Try hitting r on the affected items with nei installed
