### ISSUE TITLE
[Website] Wiki login is not working.

### ISSUE THREAD

**Issue by oddstr13** [dan200/ComputerCraft#107]
> Login error
ComputerCraft Wiki uses cookies to log in users. You have cookies disabled. Please enable them and try again. 

See [ComputerCraft Forums - Unable to log in to wiki](http://www.computercraft.info/forums2/index.php?/topic/26707-unable-to-log-in-to-wiki/)

See also [StackOverflow - Problem with mediawiki cookies](http://stackoverflow.com/questions/1148583/problem-with-mediawiki-cookies) for possible causes and solutions.

**Comment by apemanzilla** [comment]
The error seems pretty straightforward. Do you have cookies disabled by your browser?

**Comment by KnightMiner** [comment]
It's not that straightforward, the site is refusing to save cookies whether they are enabled or not

**Comment by apemanzilla** [comment]
Alright, I just tested it myself and got the same error.

**Comment by AEnterprise** [comment]
most likely it's just the webservers temp folder that filled up and needs cleaning

**Comment by dan200** [comment]
Sorted
