### ISSUE TITLE
Updating Blocks with bundled cable and blocks 

### ISSUE THREAD

**Issue by AndrewCraft-Server** [dan200/ComputerCraft#108]
https://www.youtube.com/watch?v=JX0cUpuBAss

**Comment by AEnterprise** [comment]
problem seems to be on the project red side of things as it's the red alloy wire that isn't doing it's job of updating the lamp

**Comment by dan200** [comment]
Yeah, this is the interaction between the wire and the lamp, not the computer and the wire.
