### ISSUE TITLE
Piston orientation with turtles

### ISSUE THREAD

**Issue by Pyeroh** [dan200/ComputerCraft#109]
Currently, it impossible for a turtle to place a piston oriented the way I want (eg. turtle.placeDown doesn't place the piston facing up).

I'm using CC 1.78 and MC/Forge 1.8.9

**Comment by dan200** [comment]
Yes you can, you just need a surface to place against. Only when the piston is being placed in thin-air and needs to be placed against the turtle's face do you get the opposite orientation.
