### ISSUE TITLE
Can't open file with ":" in the name

### ISSUE THREAD

**Issue by SoniEx2** [dan200/ComputerCraft#11]
I made some files "player:nbs.lua" "player:monitor.lua" etc, and they can't be opened with fs.open(). Trying to make a file "player:test.lua" from in-game removes the ":".

EDIT: Why I want to use ":"? Well, MC items are named e.g. "minecraft:stone", so I decided to name my files like that because it's better.

**Comment by dan200** [comment]
https://msdn.microsoft.com/en-gb/library/windows/desktop/aa365247%28v=vs.85%29.aspx

**Comment by SoniEx2** [comment]
I'm on Linux. Please expose the underlying FS's name rules.

**Comment by theoriginalbit** [comment]
doesn't matter that you're on Linux, ComputerCraft/Minecraft is cross-platform, colons shouldn't be used. Just replace `:` with `_`.

[Here are some other things that shouldn't be used](https://josephscott.org/archives/2007/02/things-that-shouldnt-be-in-file-names-for-1000-alex/)

**Comment by SoniEx2** [comment]
Ok... Alternatively check if the file exists as-is on the FS, if so (and you're trying to _read_ it) then use it, otherwise act "normally" (aka brokenly).
