### ISSUE TITLE
2D Rendering of objects in 1.80pr0

### ISSUE THREAD

**Issue by Senseidragon** [dan200/ComputerCraft#112]
May not be a bug if this was an intentional decision, but visually expected 3D renders of CC items (turtle, monitor, computer, etc.) in player inventory.  Items appear correct when placed in world, and appear correct (if a bit larger than normal) in hand.

MC Version 1.94
CC Version 1.80pr0

**Comment by KnightMiner** [comment]
The block model system changed for the better from 1.8.9 to 1.9.4, but it involves updating the individual model files to get the model rotations right (basically, display tags were changed, but models can now inherit them from other models better)

In general, you can just delete all the display tags on the itemblock models and add `"parent": "block/block"` to the block models.

**Comment by dan200** [comment]
Fixed in pr1
