### ISSUE TITLE
Possibly related to #111 - Graphical glitch when executing turtle movement commands.

### ISSUE THREAD

**Issue by Senseidragon** [dan200/ComputerCraft#113]
When instructing turtle to turnLeft() or turnRight(), visually the turtle doesn't seem to update until the next (non-turn) action command executes.

Test 1:  Place turtle facing North.  go into Lua and execute: turtle.turnLeft()
Expected: Turtle should be facing West.  Turtle appears to still face North.
Execute: turtle.forward()
Expected: Based on visual information, expect turtle to move 1 space North, turtle instead visually updates to face West, then moves one space West.

Test 2: Place turtle facing North. go into Lua and execute: turtle.turnLeft() turtle.turnLeft()
(yes, turn left twice)
Expected: Turtle should be facing South.  Turtle appears to be facing North.
Telling turtle to move forward at this point will cause the visual discrepancy to fix and turtle will in fact move 1 space South.

MC Version 1.94
CC Version 1.80pr0

**Comment by dan200** [comment]
Fixed. Thanks squiddev!
