### ISSUE TITLE
No collision with entities in 1.80pr0

### ISSUE THREAD

**Issue by Senseidragon** [dan200/ComputerCraft#114]
MC Version 1.94
CC Version 1.80pr0

Entities (player or mob) cannot collide with placed CC blocks.

Test: Place computer, monitor, turtle, disk drive, pretty much any placeable item in-world.
Expected: walking toward object should block movement.  It doesn't.
This is true for all entities, not just player entities.  CC objects can still be interacted with.
Water/Lava does not flow into object (as expected), pistons do not move object (as expected).

**Comment by 2000jf** [comment]
Yep, experiencing the same

**Comment by dan200** [comment]
Fixed in pr1
