### ISSUE TITLE
[1.80pr0] Active modems have the texture of a deactivated modem.

### ISSUE THREAD

**Issue by lurquhar1221** [dan200/ComputerCraft#115]
This affects 1.80pr0.

Activated wired modems have the incorrect texture.
They share the texture of a deactivated wired modem.

Activated wireless modems have the incorrect texture.
They share the texture of a deactivated wireless modem.

Activated ender modems have the incorrect texture.
They share the texture of a deactivated ender modem.

**Comment by SquidDev** [comment]
I believe this has now been fixed.
