### ISSUE TITLE
[1.80pr0] All floppy disks are white

### ISSUE THREAD

**Issue by lurquhar1221** [dan200/ComputerCraft#117]
All floppy drives use the base texture, without applying the color transformation.
They are all white.

Picture for reference: http://i.imgur.com/thFNXUP.png

( 1.9.4, Forge 12.17.0.1976, Java 1.8.0_65 64bit, no other mods loaded)

**Comment by KnightMiner** [comment]
1.9 switched from getting colors from the item to getting colors from a registered ItemColor handler. Basically the coloring just needs to be moved to a client proxy

**Comment by dan200** [comment]
Fixed
