### ISSUE TITLE
[1.80pr0] Turtle animations/model only update right clicked

### ISSUE THREAD

**Issue by lurquhar1221** [dan200/ComputerCraft#118]
Replicate by making the following program:
```while true do
    turtle.turnLeft()
end```

Now, run the program.
When right clicking the turtle, it updates what the model should look like, and plays the respective animations.

(1.9.4, Forge 12.17.0.1976, Java 1.8.0_65 64bit, No other mods loaded)

**Comment by eniallator** [comment]
this also seems to be the same for doing the equip/unequip programs where the items don't render on the turtle until you right click (although i think if you make the turtle move in a direction not just turn, it will also update the model and make it render).

**Comment by Senseidragon** [comment]
This seems to be the same behavior observed in #113 and #111.  Right-clicking seems to be another method to force an update.

**Comment by dan200** [comment]
Same as #113

**Comment by sigmasoldi3r** [comment]
Is fixed? :~
