### ISSUE TITLE
monitor.write(nil) doesn't error right

### ISSUE THREAD

**Issue by SoniEx2** [dan200/ComputerCraft#12]
monitor.write(nil) doesn't error right. I had to add a bunch of `.. ""` to find where it was erroring.

**Comment by theoriginalbit** [comment]
I would say you're doing something wrong, perhaps consider creating an account on the [ComputerCraft Forums](http://www.computercraft.info/forums2/) and jumping onto the [Ask a Pro section](http://www.computercraft.info/forums2/index.php?/forum/14-ask-a-pro/) to get assistance.

**Comment by SoniEx2** [comment]
`monitor.write(nil)` (because you forgot to initialize a variable somewhere) shows "Java threw an exception: java.lang.NullPointerException". Alternatively, `monitor.write(nil .. "")` causes an "attempt to concatenate nil and string" error, which includes line numbers, so you can actually see what's wrong instead of having to guess it.

**Comment by dan200** [comment]
This is already fixed in the latest beta
