### ISSUE TITLE
[1.80pr0] Crash with ender modems

### ISSUE THREAD

**Issue by eniallator** [dan200/ComputerCraft#120]
When i try to place an ender modem anywhere in the world (including placing it on computers), it makes my game freeze but not crash. However when i force quit minecraft and then launch it and go into the same world, it crashes me.
[crash-2016-06-28_11.04.14-server.txt](https://github.com/dan200/ComputerCraft/files/336736/crash-2016-06-28_11.04.14-server.txt)

**Comment by dan200** [comment]
Fixed in pr1

**Comment by nikkimas** [comment]
Sry to reopen this, but I do have the same problem and can't find the pr1. Curse is just giving me pr0. Could someone tell me where to find it?

**Comment by dan200** [comment]
It is not released yet

**Comment by nikkimas** [comment]
Ok okay. Thank you for the fast reply :)
