### ISSUE TITLE
[CC 1.80pr0] Monitors look weird

### ISSUE THREAD

**Issue by Luca0208** [dan200/ComputerCraft#123]
I'm not sure how to describe it, I think an Image will be the best
![2016-06-29_20 32 20](https://cloud.githubusercontent.com/assets/9638292/16464079/df426b14-3e38-11e6-8198-2902c9021422.png)

**Comment by COOLGAMETUBE** [comment]
I had that on a MC1.8.0 Beta Build as well.

**Comment by dan200** [comment]
I believe this is fixed in current
