### ISSUE TITLE
[1.9.4] Crash when placing Ender Modem

### ISSUE THREAD

**Issue by Gamerbolts** [dan200/ComputerCraft#128]
Hello I am crashing to desktop when I place an ender modem. Upon coming back into the world if I look at the ender modem again or try to break it I crash.

Here is the error log
http://pastebin.com/sLWS0mtK

Thanks for the help!

**Comment by dan200** [comment]
Already reported. 
Also: please remember this is an Alpha, you really shouldn't be using it in modpacks.
