### ISSUE TITLE
redstone Input Bug

### ISSUE THREAD

**Issue by nikkimas** [dan200/ComputerCraft#129]
When I try to read rs signals going in the COmputer, it always detects no signal. Proof Video: [https://youtu.be/TevHnzH0UTY](https://youtu.be/TevHnzH0UTY)

**Comment by KnightMiner** [comment]
What version of Minecraft/ComputerCraft? From the video, I can only tell that you are not on 1.7.10

**Comment by AEnterprise** [comment]
he's on MInecraft 1.10.2 and ComputerCraft 1.80pr0, it's in the video description

**Comment by nikkimas** [comment]
Sorry, fogot to add it here on github. 
MC: 1.10.2 
CC: 1.80pr0

**Comment by negamartin** [comment]
On Minecraft 1.9.4 with only CC1.80pr0 installed the problem still exists.
All inputs are false, all analog inputs are 0 and no "redstone" events are generated.
It doesn't matter what way you power the computer block.

**Comment by dan200** [comment]
Fixed. Thanks squiddev!
