### ISSUE TITLE
Make windows with background color 0 transparent

### ISSUE THREAD

**Issue by SoniEx2** [dan200/ComputerCraft#13]
It'd be much easier to make my thing work if color 0 didn't bother with background color... Alternatively add a way to disable background color?

**Comment by SquidDev** [comment]
- `cp /rom/apis/window customWindow`
 - `edit customWindow`
 - Profit!

**Comment by SoniEx2** [comment]
Yeah and then I can't distribute it because copyright! >.>

**Comment by SquidDev** [comment]
I can't find the source but Dan has given permission to redistribute the `rom` folders.

**Comment by SoniEx2** [comment]
Can I sell them with my program, if I ever decide to sell my program?

**Comment by dan200** [comment]
You are allowed to distribute modified versions of CC's built-in lua files, as long as they are only for use with ComputerCraft. No, you may not sell them.

**Comment by dan200** [comment]
Also, I will block you if you post another bug report that isn't a bug.

**Comment by SoniEx2** [comment]
Issues and bug reports are different things. Issues (github issues at least) aren't limited to bugs.

**Comment by theoriginalbit** [comment]
> Can I sell them with my program, if I ever decide to sell my program?

I doubt anyone would ever pay for it
