### ISSUE TITLE
[1.80pr0] Debug Menu (F3) Causes java.lang.IllegalArgumentException Hard Crash

### ISSUE THREAD

**Issue by evanjohnman** [dan200/ComputerCraft#130]
VERSION:
1.80pr0 (Via FTB Unstable 1.10)
DESCRIPTION:
It crashes.
EXPECTED RESULT:
...Not crashing? (what am I even supposed to put here?)
REPRODUCTION STEPS:
1. Launch Minecraft with CC 1.80pr0 installed.
2. Create a world.
3. Place a turtle (in my case, a mining turtle) in the world.
4. Press F3.
5. Look at the turtle.
This should result in a crash.

**Comment by evanjohnman** [comment]
Update: This also occurs (with a similar exception) with a YETA wrench.
Exception is: `java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block computercraft:CC-TurtleAdvanced, it is not an allowed value`

**Comment by supertroll** [comment]
this bug doesn't happen in my case. have you tried replicating the bug again?

**Comment by dan200** [comment]
This has been solved in pr1 (not yet released)
