### ISSUE TITLE
[1.80pr0] gps host program stuck at "opening channel on modem left"

### ISSUE THREAD

**Issue by supertroll** [dan200/ComputerCraft#132]
steps to bug
1.place computer
2.place wireless modem on computer
3.run gps host <x> <y> <z> 
the computer wil say "opening channel on modem left" and stay there

**Comment by dan200** [comment]
That's a not a bug. It opens the channels then sits and waits for GPS requests. What were  you expecting to happen?

**Comment by supertroll** [comment]
but doesn't it normally say something like "waiting for requests"?
