### ISSUE TITLE
[1.80pr0]computers don't turn on after relog into singleplayer world

### ISSUE THREAD

**Issue by supertroll** [dan200/ComputerCraft#133]
well the title says it all
and this gets fixed if the computer is broken and placed back

**Comment by paolo565** [comment]
This also happens when you are playing on a server and chunks unload.
When i try to use the computer after loading chunks again it doesn't work, i get a blackscreen and i have to break and place it to make it work again.

**Comment by paolo565** [comment]
Update:
The bug doesn't happen on turtles (tested in singleplayer and on a server).
The bug happens effects only computers even if i chunk load the chunks (tested with the ChickenChunks chunk loader on a server)

**Comment by KingofGamesYami** [comment]
Related to #95

**Comment by dan200** [comment]
Fixed. Thanks squiddev!
