### ISSUE TITLE
[1.80pr0] Turtles pointing to the south direction after reconnecting to the server

### ISSUE THREAD

**Issue by paolobarbolini** [dan200/ComputerCraft#134]
If i place a turtle on a server and i log off and then i log in again the turtle looks to be pointing towards the south direction, but after right clicking on it rotates in the correct direction.

CC Version: 1.80pr0
Forge Version: 12.18.1.2044

The turtle i just have placed:
![2016-08-03_17 19 35](https://cloud.githubusercontent.com/assets/6215781/17371031/b45fff02-599e-11e6-985c-83addc36ba84.png)

Turtle after logging in again:
![2016-08-03_17 20 33](https://cloud.githubusercontent.com/assets/6215781/17371030/b45cbd56-599e-11e6-91e8-b8ebc824c0e6.png)

Turtle after right clicking on it:
![2016-08-03_17 20 50](https://cloud.githubusercontent.com/assets/6215781/17371029/b45c4326-599e-11e6-855a-444f34e6c8b5.png)

**Comment by SquidDev** [comment]
Fixed in #154.
