### ISSUE TITLE
[1.80pr0] Monitor not working and texture bugg.

### ISSUE THREAD

**Issue by wdejonge97** [dan200/ComputerCraft#136]
No further explanation needed. I do have a screenshot. Also saw that the computer is not turning on after    joinen the world, but someone already made a threat about it. (both tested on singeplayer and server.
![2016-08-14_23 03 22](https://cloud.githubusercontent.com/assets/21026786/17652094/6b7cc00c-6274-11e6-84c3-132104191471.png)

**Comment by negamartin** [comment]
Seems like a duplicate of #123 ?

**Comment by wdejonge97** [comment]
Looks like it. I looked if someone already reported this bugg but couldnt find it. Guess I missed it.

And I found another one. When you give turtle a turn command it doesnt turn until you right-click on it again. Than it turns.

**Comment by negamartin** [comment]
That's also been reported on #113

**Comment by wdejonge97** [comment]
I guess this can be closed then

**Comment by dan200** [comment]
I believe this is fixed in current

**Comment by fcpwiz** [comment]
@dan200 Where can I find the files that contain the fix for this?

**Comment by vpontin** [comment]
@fcpwiz you need to build the source yourself OR download from @SquidDev 's build system: https://cc.crzd.me/

**Comment by fcpwiz** [comment]
Ah, thanks @vpontin !
