### ISSUE TITLE
Receiving an error!

### ISSUE THREAD

**Issue by iNightmaree** [dan200/ComputerCraft#137]
Earlier, I attached a resonant energy cell to a computer and wrapped it as a peripheral. Upon server restart, found this in the console: https://puu.sh/qCMuX/cb658975be.png

**Comment by SquidDev** [comment]
This is an OpenPeripheral problem by the looks of it: not a ComputerCraft bug.

**Comment by iNightmaree** [comment]
Oh I see, well I'll go report it to them. Thank you!
