### ISSUE TITLE
Problem with porgramm on server the server crashes

### ISSUE THREAD

**Issue by Ramog** [dan200/ComputerCraft#139]
I use [this programm](http://pastebin.com/847eEtKa) on a server and every time it runs the server crashes after some random time and since it is in the startup file the server always crashes after some time which is very annoying is there an easy fix for this?

**Comment by oddstr13** [comment]
Please provide ComputerCraft version number, and full crash log.
You can find the log in the server directory, under crash-logs.


Temporary workaround would be to remove the startup file from the computer. It can be found under <worldname>/computer/<computer id>.

On September 4, 2016 11:26:32 PM GMT+02:00, Ramog <notifications@github.com> wrote:
>I use [this programm](http://pastebin.com/847eEtKa) on a server and
>every time it runs the server crashes after some random time and since
>it is in the startup file the server always crashes after some time
>which is very annoying is there an easy fix for this?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dan200/ComputerCraft/issues/139

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Ramog** [comment]
sorry it is not my server at the admin can't give me them yet :/ , but the computercraft version is 1.75

**Comment by dan200** [comment]
This bug report contains no actionable data, sorry!
