### ISSUE TITLE
Computers shutting down and not turning on again

### ISSUE THREAD

**Issue by martinkors** [dan200/ComputerCraft#140]

**Comment by oddstr13** [comment]
``````

**Comment by gril002** [comment]
This happens when you place down a computer than close the game. After you start the game again the computers do not start up and you can not interact with it at all

**Comment by Restioson** [comment]
Which version are you on here?

**Comment by martinkors** [comment]
@Restioson  1.9.4

**Comment by SquidDev** [comment]
This has been fixed in #154.

**Comment by SquidDev** [comment]
@martinkors As the creator of the issue, you should be able to close it. Do you think you could? - It just helps make the repo that tiny bit tidier. Thanks!

**Comment by gril002** [comment]
I'm really happy Dan made Computer Craft open source and thank you too SquidDev :D
