### ISSUE TITLE
Placing an Ender modem down crashes and continues to crash on startup of the world

### ISSUE THREAD

**Issue by gril002** [dan200/ComputerCraft#142]
Putting down an Ender modem anywhere (ground, computer etc.) crashes the game. Then when I try to start the world again the game immediately crashes again. This is my first post so if I didn't include something that I should gave just let me know.
[crash-2016-09-18_16.29.31-client.txt](https://github.com/dan200/ComputerCraft/files/478768/crash-2016-09-18_16.29.31-client.txt)

**Comment by xAnavrins** [comment]
Can you provide the MC and CC version where this occurs?

**Comment by Keanu73** [comment]
I have the same issue when placing an Ender Modem on a Command Computer. One of my staff members reported this to me. Log: http://paste.ubuntu.com/23639171/

**Comment by JustPingo** [comment]
If you're using 1.10.2, I've made a quick and dirty fix.
http://www.computercraft.info/forums2/index.php?/topic/28092-mc-1102cc-180pr0-modemcrashfix-fixes-modem-crashes-duh/
Is it also happening in 1.9.4?

**Comment by SquidDev** [comment]
See #120. This has been fixed though not released yet.

**Comment by SquidDev** [comment]
This was fixed sometime in 7d497f28350c4dadffc7de0a3d15571e3ad3726d.

**Comment by dan200** [comment]
Fixed in current

**Comment by Keanu73** [comment]
Thank god.
