### ISSUE TITLE
Inefficient atlas texture space usage

### ISSUE THREAD

**Issue by sfPlayer1** [dan200/ComputerCraft#145]
CC adds several pre-stitched textures with lots of dead space to the MC texture atlas. A large atlas texture affects overall game performance severely or may even prevent the game from starting if the graphics driver's size limit is exceeded.

I have uploaded a partial atlas dump showing the problem at https://i.imgur.com/HUWv94n.png

**Comment by dan200** [comment]
Much improved in current. I don't consider this an issue anymore
