### ISSUE TITLE
turtle api inconsistencies

### ISSUE THREAD

**Issue by DoWhileGeek** [dan200/ComputerCraft#148]
`turtle.getItemDetail()` returns a table with a `name`, a `count`, and a `damage` property.

the family of `turtle.inspect` methods return a `name` and `metadata`.

If `damage` and `metadata` are the same, why should they have different property names?

**Comment by SquidDev** [comment]
[Dan has said](http://www.computercraft.info/forums2/index.php?/topic/22846-173-turtleinspect-and-turtlegetitemdetail-have-different-keys-for-damage/) he won't change this.

**Comment by dan200** [comment]
They've not the same.
turtle.inspect() returns information about blocks
turtle.getItemDetail() returns information about items
Blocks don't have damage values
Items don't have metadata
