### ISSUE TITLE
Turtle Name

### ISSUE THREAD

**Issue by LCAdmin** [dan200/ComputerCraft#15]
This isn't really an issue, but something I've been struggling with the past week. I couldn't find a better place to post this than here. What I'm trying to do is find a certain name for turtles. The name is supposed to be used in a format similar to:  ThermalExpansion:Strongbox, ThermalExpansion:Cache, or MineFactoryReloaded:machine.1. I've tried multiple variations of the name. BlockType, Class name, real name, different capitalization-- I've tried a lot. Not one of my guesses has been successfully recognized. All of them are listed here: http://pastebin.com/8cNP9tpH . I've tried googling around to find the right answer, but nothing has helped me. I was hoping some of you might be able to help a brother out by offering your thoughts on what name is supposed to be used.

**Comment by SquidDev** [comment]
It you type `/give @p ComputerCraft:` and then press <kbd>tab</kbd> it should list all available items. This gives you:
 - `ComputerCraft:CC-Turtle` - Normal turtles,
 - `ComputerCraft:CC-TurtleAdvanced` - Advanced ones

**Comment by LCAdmin** [comment]
It worked! Thank you so much! Thanks for also teaching me the method. From talking in the IRC, I understand that this actually belongs in the forums, so sorry for that :\
