### ISSUE TITLE
Turtles Exploding

### ISSUE THREAD

**Issue by tincopper2** [dan200/ComputerCraft#16]
There is a problem when mining in the nether with turtles (netherores) or having creepers explode next to turtles, where the turtle disappears. I believe it should be an option in the config to have this happen, or an option so advanced turtles are more blast resistant and tnt proof.

**Comment by dan200** [comment]
Turtles are already resistant to Creeper and Ghast explosions.

**Comment by tincopper2** [comment]
Tnt and netherores blow them up, I was wondering if you could make them as resistant as obsidian

**Comment by dan200** [comment]
advanced turtles are now resistant to explosions
