### ISSUE TITLE
Add gitter chat for ComputerCraft?

### ISSUE THREAD

**Issue by JLLeitschuh** [dan200/ComputerCraft#187]
As a person interested in contributing it would be awesome to be able to chat with other devs in a instant message type format.

@dan200 You would need to set this up as you are the repo owner.

If you are interested, simply sign in to gitter, create a chat for this repository, and add the gitter badge to the readme.

https://gitter.im

Thanks!

**Comment by SquidDev** [comment]
ComputerCraft does have an [IRC](http://webchat.esper.net/?channels=#computercraft) chat which would also allow the same thing. It doesn't see much activity, but it's relatively well "established".

**Comment by CrazedProgrammer** [comment]
IRC doesn't allow for a permanent message history without manually setting up a history client-side, and Gitter has very useful markdown features.

**Comment by simon816** [comment]
FYI there is a logger bot in #computercraft
http://sbnc.khobbits.co.uk/log/logs/computercraft.htm

**Comment by Restioson** [comment]
We could make an official discord? We already have an unofficial discord, but it's also for OC.

**Comment by CrazedProgrammer** [comment]
Nah, Discord is not a good platform for development.

**Comment by Restioson** [comment]
Ah, I misunderstood the purpose of the chat room. I thought it was for support, not development.

**Comment by CrazedProgrammer** [comment]
For support you can just go to the "Ask a Pro" section on the forums :P

**Comment by MineRobber9000** [comment]
owed/Silica on gitter is used for CC discussion already.

**Comment by MineRobber9000** [comment]
I meant owed/Silica.

**Comment by MineRobber9000** [comment]
oeed/Silica on gitter is used for CC discussion already.

**Comment by LeoVerto** [comment]
@CrazedProgrammer if you want permanent history and markdown, I can very much recommend [Matrix](https://matrix.org/) which includes bridges for IRC, Gitter and a whole lot of other services.
