### ISSUE TITLE
Website: Some download links for files hosted on curseforge seem outdated.

### ISSUE THREAD

**Issue by oddstr13** [dan200/ComputerCraft#19]
Versions: 1.57 - 1.63

Current links for your convenience:
 * 1.63 - http://minecraft.curseforge.com/projects/computercraft/files/785780/download
 * 1.62 - http://minecraft.curseforge.com/projects/computercraft/files/782866/download
 * 1.61 - http://minecraft.curseforge.com/projects/computercraft/files/782322/download
 * 1.60 - http://minecraft.curseforge.com/projects/computercraft/files/781298/download
 * 1.58 - http://minecraft.curseforge.com/projects/computercraft/files/758858/download
 * 1.57 - http://minecraft.curseforge.com/projects/computercraft/files/746767/download

**Comment by dan200** [comment]
Fixed. Thanks
