### ISSUE TITLE
Suggestion: New/improved models

### ISSUE THREAD

**Issue by ObloxCC** [dan200/ComputerCraft#202]
Computercraft just uses the block model for its computers and I was wondering if anyone would like to (a) create new models, or (b) agree that I should try to make some. These models should keep with the computercraft feel by (c) only adding some 3D elements but keeping the block feel, or (d) making the front look the same and cutting down the block size by 1/2.

**Comment by Techokami** [comment]
Models are expensive (in the rendering sense) in Minecraft now. It'd be best to keep things as block models, OR have models be an option that can be easily disabled and not affect collisions.

**Comment by Restioson** [comment]
Wouldn't it be confusing if it had a different model to it's blockmodel?

**Comment by KnightMiner** [comment]
I kinda like the block, it's pretty classic.

Models are not expensive, the whole point of the json system is to make them cheap.

**Comment by ObloxCC** [comment]
Ill try to make an example sometime today

**Comment by ObloxCC** [comment]
Something like this:
http://imgur.com/7efDh5p
http://imgur.com/lTM0R7g
http://imgur.com/2GrYQR8

**Comment by ObloxCC** [comment]
{
    "textures": {
        "0": "computercraft:blocks/computerSideAdvanced",
        "1": “computercraft:blocks/computerFrontAdvanced",
        "2": "computercraft:blocks/computerTopAdvanced"
    },
    "elements": [
        {
            "name": "Cube",
            "from": [ 0.0, 0.0, 0.0 ], 
            "to": [ 16.0, 16.0, 15.0 ], 
            "faces": {
                "north": { "texture": "#0", "uv": [ 0.0, 0.0, 16.0, 16.0 ] },
                "east": { "texture": "#0", "uv": [ 0.0, 0.0, 16.0, 16.0 ] },
                "south": { "texture": "#1", "uv": [ 0.0, 0.0, 16.0, 16.0 ] },
                "west": { "texture": "#0", "uv": [ 0.0, 0.0, 16.0, 16.0 ] },
                "up": { "texture": "#2", "uv": [ 0.0, 0.0, 16.0, 16.0 ] },
                "down": { "texture": "#2", "uv": [ 0.0, 0.0, 16.0, 16.0 ] }
            }
        },
        {
            "name": "OutlineL1",
            "from": [ 0.0, 0.0, 15.0 ], 
            "to": [ 1.0, 16.0, 15.5 ], 
            "faces": {
                "north": { "texture": "#1", "uv": [ 0.0, 0.0, 1.0, 16.0 ] },
                "east": { "texture": "#1", "uv": [ 0.0, 0.0, 0.5, 16.0 ] },
                "south": { "texture": "#1", "uv": [ 0.0, 0.0, 1.0, 16.0 ] },
                "west": { "texture": "#1", "uv": [ 0.0, 0.0, 0.5, 16.0 ] },
                "up": { "texture": "#1", "uv": [ 0.0, 0.0, 1.0, 0.5 ] },
                "down": { "texture": "#1", "uv": [ 0.0, 0.0, 1.0, 0.5 ] }
            }
        },
        {
            "name": "OutlineR1",
            "from": [ 15.0, 0.0, 15.0 ], 
            "to": [ 16.0, 16.0, 15.5 ], 
            "faces": {
                "north": { "texture": "#1", "uv": [ 0.0, 0.0, 1.0, 16.0 ] },
                "east": { "texture": "#1", "uv": [ 0.0, 0.0, 0.5, 16.0 ] },
                "south": { "texture": "#1", "uv": [ 0.0, 0.0, 1.0, 16.0 ] },
                "west": { "texture": "#1", "uv": [ 0.0, 0.0, 0.5, 16.0 ] },
                "up": { "texture": "#1", "uv": [ 0.0, 0.0, 1.0, 0.5 ] },
                "down": { "texture": "#1", "uv": [ 0.0, 0.0, 1.0, 0.5 ] }
            }
        },
        {
            "name": "OutlineB1",
            "from": [ 1.0, 0.0, 15.0 ], 
            "to": [ 15.0, 1.0, 15.5 ], 
            "faces": {
                "north": { "texture": "#1", "uv": [ 0.0, 0.0, 14.0, 1.0 ] },
                "east": { "texture": "#1", "uv": [ 0.0, 0.0, 0.5, 1.0 ] },
                "south": { "texture": "#1", "uv": [ 0.0, 0.0, 14.0, 1.0 ] },
                "west": { "texture": "#1", "uv": [ 0.0, 0.0, 0.5, 1.0 ] },
                "up": { "texture": "#1", "uv": [ 0.0, 0.0, 14.0, 0.5 ] },
                "down": { "texture": "#1", "uv": [ 0.0, 0.0, 14.0, 0.5 ] }
            }
        },
        {
            "name": "OutlineT1",
            "from": [ 1.0, 15.0, 15.0 ], 
            "to": [ 15.0, 16.0, 15.5 ], 
            "faces": {
                "north": { "texture": "#1", "uv": [ 0.0, 0.0, 14.0, 1.0 ] },
                "east": { "texture": "#1", "uv": [ 0.0, 0.0, 0.5, 1.0 ] },
                "south": { "texture": "#1", "uv": [ 0.0, 0.0, 14.0, 1.0 ] },
                "west": { "texture": "#1", "uv": [ 0.0, 0.0, 0.5, 1.0 ] },
                "up": { "texture": "#1", "uv": [ 0.0, 0.0, 14.0, 0.5 ] },
                "down": { "texture": "#1", "uv": [ 0.0, 0.0, 14.0, 0.5 ] }
            }
        },
        {
            "name": "Power1",
            "from": [ 12.0, 2.0, 15.0 ], 
            "to": [ 14.0, 3.0, 15.3 ], 
            "faces": {
                "north": { "texture": "#1", "uv": [ 12.0, 13.0, 14.0, 14.0 ] },
                "east": { "texture": "#1", "uv": [ 12.0, 13.0, 12.3, 14.0 ] },
                "south": { "texture": "#1", "uv": [ 12.0, 13.0, 14.0, 14.0 ] },
                "west": { "texture": "#1", "uv": [ 13.0, 13.0, 13.3, 14.0 ] },
                "up": { "texture": "#1", "uv": [ 12.0, 13.0, 14.0, 13.3 ] },
                "down": { "texture": "#1", "uv": [ 12.0, 13.0, 14.0, 13.3 ] }
            }
        }
    ]
}

**Comment by Restioson** [comment]
@ObloxCC please, *please* make this into a gist. This is taking up way too much space.

**Comment by lurquhar1221** [comment]
I'd prefer this to be _optional_, and off by default.

**Comment by vpontin** [comment]
And I'd prefer this to be the default, because 3d-lized is awesome!

**Comment by vpontin** [comment]
@ObloxCC sorry to necro this issue, but how about to make a resource pack for that? Since you only shared one json (for advanced computer) i was unable to make this myself. Thanks!
