### ISSUE TITLE
[Enhancement] Idea: man pages

### ISSUE THREAD

**Issue by Restioson** [dan200/ComputerCraft#212]
It would be useful if we could have a command line utility to print out a lengthy help page for a utility, essentially the `man` command from *nix. We could store the man page in the same folder as the program, with the same name as the program, and with the extension `.man.txt`, or we could store it at `/man/program_name/man.txt`. This is just a thought.

**Comment by Lignum** [comment]
There's the `help` program.

**Comment by Restioson** [comment]
Can you do `help pastebin`? I'll try it out in a sec.

**Comment by Lignum** [comment]
You can, it even works with most APIs. Try `help term`.

**Comment by SquidDev** [comment]
Yeah, `help` exists. However, it would be nice if it `less`-like pagination. For instance: step forwards/back with arrow keys and page-up/down\*, quit early with `q`, etc...

\*: Sure, you can also use C-f to move forwards, but ctrl keys are a faff to add and probably not needed.

**Comment by apemanzilla** [comment]
@SquidDev I've been (sort of) working on some changes to the `textutils` library and that's one of the things I plan to implement.

**Comment by CrazedProgrammer** [comment]
This would be very nice, I love manpages!

**Comment by ObloxCC** [comment]
I could try to fix up the help system if you want?

**Comment by dan200** [comment]
We already have "help".

**Comment by SquidDev** [comment]
@dan200 There have been some comments that the built-in help files aren't always that useful. Part of these files' usefulness is limited by the method by which they are read (`help`). What would your stance be on someone contributing a more powerful help browser? What form this takes is probably up for discussion.

**Comment by Restioson** [comment]
Cool, was just an idea :smile:
