### ISSUE TITLE
Server crash on startup?

### ISSUE THREAD

**Issue by Wojbie** [dan200/ComputerCraft#22]
I tried to run CC server locally for me and fiends.
It crashed on startup and spew out this:
http://pastebin.com/B8phY71t

**Comment by SquidDev** [comment]
I'd guess there are some `@SideOnly`s missing. I'm pretty sure `ITurtleUpgrade.getModel` should have one as well.

**Comment by columna1** [comment]
I also tried starting a server for public testing but got this http://pastebin.com/AJ1esvxa

**Comment by dan200** [comment]
Working on this one now. I always forget to test on dedicated...

**Comment by dan200** [comment]
Fixed for 1.76pr1
