### ISSUE TITLE
Sources for older ComputerCraft versions

### ISSUE THREAD

**Issue by sci4me** [dan200/ComputerCraft#226]
Is getting the source code to older versions of ComputerCraft feasible? I am specifically interested in 1.75.

**Comment by oddstr13** [comment]
The Lua part is available here; https://github.com/alekso56/ComputercraftLua/

As for the Java part;
@dan200 have you applied the current license to all past releases, or would you consider doing this?
Thus, people could decompile, fix and recompile old versions if they so wish.

**Comment by Techman749** [comment]
I second this. I'd really love to be able to tinker around with the source code for 1.75 since it runs on Minecraft 1.7.10. Most of the mods I and a few of friends play with are still on 1.7.10 and I'd like to be able to tinker with this mod for that version of the game.

**Comment by dan200** [comment]
It is not feasible for me to release older CC source code because of ComputerCraftEdu (which I do not own). I had to do some work to unpick the CCEdu stuff from CC before this release, and I don't fancy doing it again.

It also goes against the whole poijnt of open sourcing CC: which was to keep the mod up to date with new versions.

**Comment by lupus590** [comment]
@dan200 would you be allowed to pass the source to an individual to remove the CCEdu stuff on your behalf?

**Comment by clienthax** [comment]
Im only seeing two files that reference computercraftedu in 1.75 (recently had to decompile everything to fix the redstone crasher bug), @dan200 I wouldn't mind doing this for you, i understand that its against the point of the release, but the current last build of 1.7.10 has some pretty nasty bugs in it.
