### ISSUE TITLE
Crash when turtle hits mob

### ISSUE THREAD

**Issue by Creeper9207** [dan200/ComputerCraft#24]
Using Advanced turtle with pickaxe excavating a 2x2 landform, i dropped a creeper in, when it hit it it froze and crashed
Crash report: http://pastebin.com/N9WVcev8

**Comment by columna1** [comment]
I can duplicate this. It seems like when the creeper gets inside of the turtle and falls down a block and starts sufficating it crashes.

**Comment by Wojbie** [comment]
I think this is related issue. Happen to me when turtle moved (or attacked not sure) into my player on head Level.. http://pastebin.com/THCP3bZw

**Comment by dan200** [comment]
Fixed for 1.76pr1, thanks!
