### ISSUE TITLE
Sugestion: Ability to remove CraftOS

### ISSUE THREAD

**Issue by ObloxCC** [dan200/ComputerCraft#240]
Before trying to implement this, I was wondering if anyone would find it useful for the ability to remove CraftOS off of any computer (like a `rm craftos` or something). What I mean by this is that every computer still comes preloaded with craftos, but you can remove it from each individual computer **without** modifying the jar file **or** using a resource pack. This could be useful when developing a computercraft os (more than just GUI for CraftOS). It possibly could be similar, but different to OpenComputers where you can install the different OSes, but with this CraftOS would be installed by default.

**Comment by KnightMiner** [comment]
I honestly don't see the point. It is easy enough using the startup file to start your own custom OS and then shutdown when that shuts down, so why remove the OS entirely when it is basically just a command line?

**Comment by SquidDev** [comment]
@KnightMiner: The only real use I can see is the ability to escape the shell and the rednet coroutine. Though this can be done with a TLCO, so there isn't much benefit.

I don't think being able to delete the `rom` folder makes much sense. If we're going for the ability to have a "bare bones" system, I rather like @apemanzilla's suggestion of [custom ROM via crafting](http://www.computercraft.info/forums2/index.php?/topic/17351-custom-rom-via-crafting/), allowing one to "swap out" the `rom` folder through crafting a computer with a disk.

**Comment by ObloxCC** [comment]
So maybe I could try to add either a ROM flashing API, or a ROM flashing block?

**Comment by jordansinn1994** [comment]
I don't think OpenComputers should be used as the standard for what ComputerCraft should be. I'm also unsure why you give yourself "thumbs up" on all your comments, it's not fooling anyone.

**Comment by ecktec** [comment]
maybe extract the craftos part from `bios.lua` into `rom/boot` and write something in bios.lua to execute `boot` or, if it doesn't exist, `rom/boot`

**Comment by CrazedProgrammer** [comment]
I don't think this is a good idea. We already have a `startup.lua` which you can use to customise your environment completely.

**Comment by ecktec** [comment]
@CrazedProgrammer But doing it in `startup` means overwriting everything, while splitting it up means doing it in a less hacky way. It‘s a philosophic thing.
