### ISSUE TITLE
Full Unicode

### ISSUE THREAD

**Issue by Wilma456** [dan200/ComputerCraft#244]
Full Unicode would be nice. e.g. ↓,↑,☑,☒,☹

**Comment by dan200** [comment]
The switch to a utf8 representation for strings would break too many existing programs, including a lot of CraftOS, and Lua 5.1 doesn't even have the utf8 API. The current iso-8859-1 string representation was chosen as the best compromise for this.

(As an aside, this is fixed in CraftOS 2.0)
