### ISSUE TITLE
Change speaker playNote to take rightclick ticks instead of pitch

### ISSUE THREAD

**Issue by Cruor** [dan200/ComputerCraft#247]
Using pitch for the `playNote` function is not intuitive unless you know music theory or by googling a chart. Counting the amount of times you have right clicked the block however is trivial, and is way more intuitive to use without having to look up details online. 

For example, if you want to play the note currently you would do `pitch = 2^(n / 12)` where `n` is the amount of steps relative to the base tune value (F#4). For example G#4 is  `pitch = 2^(2 / 12)`. Even with knowledge about music theory, this isn't completely foolproof, as the base tune value would be expected to be A4 and not F#4.

Here is a snippet in Lua to convert the amount of "ticks" on the note block to the correct pitch, however i believe this should be the default behavior of the function. `2^((tick % 25 - 12) / 12)` where % is the modulo operator.

**Comment by dan200** [comment]
I'd be happy to merge this change

**Comment by Cruor** [comment]
This is apparently the current behavior of the `playNote` function. I was going by the examples posted in the PR so my bad on that one. Going to PR a help file atleast.
