### ISSUE TITLE
Suggestion: Built in chunk-loader

### ISSUE THREAD

**Issue by zachary-D** [dan200/ComputerCraft#256]
I would think that having a chunk loader built into PC's would be a good feature to have, especially in settings where a computer is running as a control server/service.  This could be a setting in the config file to enable/disable it, if admins don't want computers keeping chunks loaded, and the option could be set computer-by-computer, for example, you could have your core server PC always loaded, but only load interfaces you have scattered around normally (when players are nearby).  You could also probably apply this exclusively to the computer instead of the entire chunk, possibly just running the code on it without actually loading the chunk (turtles wouldn't work for this though).

I don't really know much of the core workings of CC or Minecraft, I usually have to install a chunkloader along with CC to run servers, so I though I'd add this as a suggestion.

**Comment by lurquhar1221** [comment]
If this was implemented, as a server owner, I would want the ability to disable chunkloading in the CC config.

**Comment by zachary-D** [comment]
On large servers you'd probably have to, but on smaller servers I think it'd be useful (in moderation).

**Comment by KingofGamesYami** [comment]
Smaller servers typically have less RAM to waste chunkloading random computers.  I think chunkloading limited to command computers would be OK.

**Comment by zachary-D** [comment]
I meant small servers in terms of userbase, not actual power.  I've got a server that has plenty of ram to use for that kind of stuff, but only myself and 4-5 friends play on it, and it runs fine.

**Comment by sci4me** [comment]
I think all types of computers, and turtles, should have an option to automatically load chunks. But of course it should be configurable! This way server owners can disable or limit it or whatever. Could be very helpful though, I think.

**Comment by zachary-D** [comment]
Limiting it to advanced/command computers seems like a good way to 'balance' the game, similar to color vs black and white on advanced and normal computers.  That could just be a default though, you could still have it controlled by config file

**Comment by KnightMiner** [comment]
I have always felt that free (non fuel consuming) chunk loaders are a overpowered when many mods add one that requires fuel. There are already quite a few powerful features of computers, I don't think chunkloading needs to be one of them 

In addition, coding and debugging a chunkloading can be painful I've heard. There have been many chunkloaders that cause world corruption before, among many issues with loading upon world load.

**Comment by dan200** [comment]
This seems a complicated and unnecessary thing to add to CC, especially
when dedicated mods exist just to add chunkloaders.

**Comment by zachary-D** [comment]
True, although the block chunk loaders wouldn't work well with turtles (if they're going any distance).

**Comment by dan200** [comment]
MiscPeripherals used to add a chunk-loading turtle upgrade back in the day. Feel free to release a modern version!

**Comment by zachary-D** [comment]
I think I may... (after I figure out how to)
