### ISSUE TITLE
Missing pixels on turtle upgrades

### ISSUE THREAD

**Issue by SquidDev** [dan200/ComputerCraft#27]
![](http://i.imgur.com/8WwieRd.png?1)

Not sure why this is happening, I guess you could disable backface culling.

**Comment by dan200** [comment]
Can't reproduce this. Can you confirm this is a regular Mining Turtle (not your own upgrade), and that you don't have any resource packs installed that change the model of the pick?

**Comment by SquidDev** [comment]
Normal upgrade with no resource packs in a dev environment. My computer is ancient so that may be something to do with it.

**Comment by dan200** [comment]
Is there any upgrade attached to the other side of the turtle?

**Comment by SquidDev** [comment]
In this case yes, but I can reproduce without one.

**Comment by dan200** [comment]
Can you create a new superflat world, select a mining turtle from the creative menu, place it at your feet facing north, and tell me the co-ordinates of the turtle

**Comment by SquidDev** [comment]
I'm not currently on my home computer - I'll have a go this evening. Sorry.

**Comment by dan200** [comment]
No worries.

**Comment by apemanzilla** [comment]
Also, do you by chance have advanced OpenGL enabled? I've had related problems with different mods, where some faces of a texture would disappear.

**Comment by SquidDev** [comment]
Screenshot with debug view.
![](http://i.imgur.com/YroeOGz.png)

I tried a pickaxe in an item frame but that renders fine. I tried several other items(pork and steak) but they rendered correctly.

**Comment by dan200** [comment]
Alright. I can't replicate this. Closing, but will re-open if anyone else reports it.
