### ISSUE TITLE
[Suggestion] built in peripherals

### ISSUE THREAD

**Issue by lupus590** [dan200/ComputerCraft#275]
it wouldn't work with everything but I think it would be cool to have a config option to have peripherals built into the computers.

It would only be doable from the config file. Built-in peripherals could be accessible via a virtual network within the computer.

Basically, I want to be able to do [this](https://github.com/dan200/ComputerCraft/issues/270#issuecomment-302950178) as I mentioned in #270 .

>On the subject of turtles. Perhaps having them being able to use tools directly? Kind of like CCTweaks Tool Host but built into the turtle (and also how OC does its robots if I understand correctly).
>Basically being able to have two peripherals and a tool(e.g. a pickaxe), with the tool being used 'from' the turtle's inventory.

**Comment by Restioson** [comment]
What would the API look like?

**Comment by lupus590** [comment]
On the Lua side? I would hope it would act similar to how we wrap peripherals on a wired network.

No idea for the Java side.

**Comment by Restioson** [comment]
Java side is not really a problem. You could subclass the various `IPeripheral`s

**Comment by dan200** [comment]
please keep this issues page for bugs, not feature requests
