### ISSUE TITLE
[Suggestion] Turtles get buffs when in range of (vanilla) beacons

### ISSUE THREAD

**Issue by lupus590** [dan200/ComputerCraft#276]
Suggested by @SquidDev  [here](https://github.com/dan200/ComputerCraft/issues/274#issuecomment-302953395) on #274 .

Basically, allow turtles to get benefits from beacon effects (and maybe potions?).

Haste (or whatever the speed boost one is called) could either make turtles move faster or reduce the fuel cost (which would make fuel values floats which might cause issues. Maybe this isn't the best example).

**Comment by SquidDev** [comment]
Copying an extract from my follow up comment:

> I'm more interested in exposing the functionality to allow those sorts of features than implementing the features themselves. This way you give other peripheral developers the same power and flexibility as the mod itself.

> Detecting beacons and responding to them requires some rather ugly hacks and I'm not entirely sure how efficient it would be - something which would have to be investigated before jumping in.

There are two solutions I can think of:
 - Iterating over the `World.tickableTileEntities` set and determining whether they are within range and are beacons.
 - Getting all loaded chunks within a 24 chunk radius (max radius of a beacon), and looping through their TEs determining whether they are a beacon and within range

Neither are especially appealing, but I guess are still worth looking into.

**Comment by KnightMiner** [comment]
I am not sure how much it fits with turtles lore wise given they are machine rather than living, plus they are missing a few of the stats beacons boost. Might make more sense to have something dedicated to turtles instead boosting them.

**Comment by lupus590** [comment]
So having them equip a beacon block gives boosts?

**Comment by Wojbie** [comment]
> reduce the fuel cost (which would make fuel values floats which might cause issues. Maybe this isn't the best example).
You could keep fuel integer and just have random chance proportional to haste level for movement event not to use fuel.

**Comment by KnightMiner** [comment]
I was thinking closer to turtle beacon like block to increase efficiency of turtles in the area. Easier to code since it is our own block, but probably would not fit best in base CC.

**Comment by lupus590** [comment]
Random idea, in my opinion definitely not fitting to CC, turtles 'worship' this beacon block by spending their fuel points and give a boost to themselves and other nearby turtles.

Another idea, vanilla beacon but replace the metal blocks with computers/turtles/redstone blocks.

**Comment by SquidDev** [comment]
I feel this is very quickly becoming a separate add on mod, and not something which really fits within CC itself.

**Comment by lupus590** [comment]
@SquidDev agreed, closing

Perhaps if someone wants to make a CC based magic addon mod?
