### ISSUE TITLE
[Discussion] Thoughts on built in package manager?

### ISSUE THREAD

**Issue by lupus590** [dan200/ComputerCraft#283]
Should we have one?

If so, a new one or one that someone has made already? If premade, which one?

**Comment by Wilma456** [comment]
I would like a this! But there's one problem: Whats with the repos? In Packman the repos are downloaded to the Computer. But if this got a part of CC, almost every, who made a program for CC want his own repos. That's to much for a Computer. In oppm (OpenComputers) the repos are just in the internet, but It's very slow.

**Comment by CrazedProgrammer** [comment]
Well, this is hard. It would make CraftOS rather bloated, in addition to inherently being less extensible than a separate package manager. If it had very good dependency management and forum-crawling (as in, it searches for pastebin links in forum posts), I could accept it. As it stands though, I'm not convinced this is a great idea.

**Comment by MineRobber9000** [comment]
I personally am against this. If we need an official package manager, however, I think we could mainstream `packman` by lyqyd. If he could fix it to work with the betas, that would be a possible decision.

**Comment by Wilma456** [comment]
@MineRobber9000 Packman is updated and works now with the beta.

**Comment by dan200** [comment]
please keep this issues page for bugs, not feature requests
