### ISSUE TITLE
Turtle mining banner wipes its contents.

### ISSUE THREAD

**Issue by Wojbie** [dan200/ComputerCraft#29]
If turtle mines any banner it gets black banner with all customization wiped out.

**Comment by dan200** [comment]
This issue can only be fixed by Forge, I have issued a report there:
https://github.com/MinecraftForge/MinecraftForge/issues/2258

**Comment by LinkTheProgrammer** [comment]
Isn't there a way to fix it yourself in the meantime by saving the customization of the block currently breaking, then apply them to the item when it is dropped?

**Comment by dan200** [comment]
No, Block NBT and Item NBT aren't convertible in a general case way, and
I'm not adding special case code just for banners.

**Comment by LinkTheProgrammer** [comment]
I never knew you couldn't convert a BlockEntityTag to ItemEntityTag. How then do banners and other items keep the customizations of the BlockEntity that drops it?

**Comment by dan200** [comment]
They have specific code in the block class for banners. This code just
hasn't been adapted to the forge getDroppedItems() hook that CC uses.

**Comment by LinkTheProgrammer** [comment]
Right, that method in Block that gives all the types of ItemEntities that BlockEntity drops (am I right?). Suppose this Banner is a child of BlockEntity (TileEntity), then how is forge not already hooking this method if it is in every BlockEntity? Or is Mojang doing the unspeakable and making code specific to a subclass of BlockEntity available in BlockEntity and would be why the hook is not yet available?

**Comment by dan200** [comment]
BlockBanner does not implement Block.getDrops(), that is all.

**Comment by LinkTheProgrammer** [comment]
Well that's annoying 😕

**Comment by dan200** [comment]
Closing this, it's in forge's court now

**Comment by dan200** [comment]
This is now solved in Forge.
Thanks Lex! https://github.com/MinecraftForge/MinecraftForge/commit/4672f7bab09523e2698d3f5a00c1cae38dbadd18
