### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by vpontin** [dan200/ComputerCraft#294]
Hi guys! How’s it going?

I want to know if Dan and the staff would welcome a localization PR, because i'm making a resource pack translating some mods to Portuguese (Brazil) and if you guys like the idea i could PR to this repository.

The repo is: https://github.com/vicocraft/vicocraft_lang

**Comment by Wojbie** [comment]
According to #5 localization is only supported as resource pack and will not be part of main mod. Unless that changed since then all localization will have to stay as resource pack only.

**Comment by dan200** [comment]
I would probably accept PR's for built in localisations now.
