### ISSUE TITLE
[Question] Support for custom models in Resource Packs

### ISSUE THREAD

**Issue by vpontin** [dan200/ComputerCraft#296]
Sorry to resurrect this issue, but does ComputerCraft 1.80 w/ Unborked 1.11.2 supports resource packs? I tried to adapt @ObloxCC 's model proposed in #202 (repository for the custom resource pack [here](https://github.com/vicocraft/computercraft_3d)) but it gives me the checkered texture and the computer won't rotate when placed:

![2017-05-30_13 08 59](https://cloud.githubusercontent.com/assets/3485505/26593077/38aecd98-4539-11e7-8bc4-fd985391b447.png)

So my question is: Does ComputerCraft (specifically 1.80 w/ Unborked for 1.11.2) accepts custom models via resource packs or the model json is somewhat messed up?

Thanks for the patience

**Comment by dan200** [comment]
I can think of no reason why it wouldn't accept them.

**Comment by SquidDev** [comment]
In each file you define the textures as `top`, `side` and `front`. However the models just refer to `0`, `1` and `2`. [The PR here](https://github.com/dan200/ComputerCraft/pull/210/files) looks like it uses the correct keys, so you might want  to copy the files from there.

**Comment by vpontin** [comment]
Thanks a lot Mr. @SquidDev , i will switch to 1.11.2 PR, use the PR you've indicated and wait for CCTweaks and Plethora to be updated 😜

**Comment by vpontin** [comment]
Actually i have a problem with the 1.11.2 CC fork @SquidDev have pointed.
https://gist.github.com/vpontin/4d370501df06d2fa1f8c45c878fe71f4
But i dont know where i would file an issue

**Comment by KnightMiner** [comment]
The build task in Gradle does not currently copy the luaj dependency into the jar. You will have to either use the deploy script or just copy the luaj jar from libs.

**Comment by ObloxCC** [comment]
@vpontin If you want or need any help with this you can message/ask me. Also if you want I can fix the models to use the correct naming.

**Comment by vpontin** [comment]
@KnightMiner thanks a lot! I will try to build myself the fork.
@ObloxCC Sadly GitHub doesnt have any PM feature, so i'll throw up the problem here: When i place a Computer using your model, it always face the opposite direction it should be. If you look [my repository](https://github.com/vicocraft/computercraft_3d) you will see the only commit i've made was fixing 1.11.x item names, I tried to fix myself but no avail, and i've tried to open the model on the MrCrayfish's Model Creator, and it wont open.
Thank you a lot for offering to help me, and feel free to PR the repo with changes!

**Comment by vpontin** [comment]
@KnightMiner sadly i cant managed to build @SquidDev 's fork correctly, due to the problem Knight mentioned before (the compilation process doesnt account the luaj library).

**Comment by SquidDev** [comment]
@vpontin Sorry, until #186 is merged you'll also need to include [luaj-jse-2.0.3.jar](https://github.com/dan200/ComputerCraft/raw/master/libs/luaj-jse-2.0.3.jar) in the `mods` folder. Alternatively use the `./deploy.sh` script and use the jar in the `deploy` folder.
