### ISSUE TITLE
There are some unlocalized variables/functions in lua programs. Also stray ’ in help/changelog.

### ISSUE THREAD

**Issue by Wojbie** [dan200/ComputerCraft#30]
Reposting from.
http://www.computercraft.info/forums2/index.php?/topic/23448-175smpssp-rom-program-functions-in-env/
 I know its kinda old but it should be fast to fix with line numbers.

```
adventure:610: attempt to create global function "doCommand" in the current environment
adventure:476: attempt to create global function "findItem" in the current environment
worm:20: attempt to create global function "printCentred" in the current environment
help:1: attempt to create global table "tArgs" in the current environment
monitor:2: attempt to create global function "printUsage" in the current environment
edit:31: attempt to create global number "stringColour" in the current environment
redirection:178: attempt to create global table "fLevel" in the current environment
```

Also there is a letter ’ in the help/changelog file in line 124 "Conway’s Game of Life" that makes said file not readable correctly in-game. Reposting from: http://www.computercraft.info/forums2/index.php?/topic/24475-174-stray-%E2%80%99-in-changelog/

**Comment by dan200** [comment]
Fixed for 1.76pr3
