### ISSUE TITLE
Monitor rendering on Mac.

### ISSUE THREAD

**Issue by dannysmc95** [dan200/ComputerCraft#300]
I noticed this while testing the nightly build server, but on my MacBook Air, I see the following https://pasteboard.co/1nAoq5pKq.png
When looking at monitors.

**Comment by BombBloke** [comment]
Are you complaining about the black panel, or are you complaining about the white dots? #56

**Comment by Lignum** [comment]
It's a wild guess, but these kinds of artifacts (including the ones in #56) look sort of like [this SO question](https://gamedev.stackexchange.com/questions/74420/seamless-tilemap-rendering-borderless-adjacent-images). Could be the same issue, but more subtle in our case, possibly due to influence by AA/aniso.

**Comment by DevelopedLogic** [comment]
I get the same issue. mine is a bit more obvious though. I've provided a screenshot similar to Danny's, and a close-up one which clearly shows that these dots are artifacts between the lines on characters on the screen, almost as though the character lines are not lined up properly. I never used to have this issue with an older version of CC, can't remember which one though.
![2017-07-05_07 30 12](https://user-images.githubusercontent.com/28887353/27851768-259beca4-6154-11e7-98b5-b6fd1bb38bf6.png)
![2017-07-05_07 30 18](https://user-images.githubusercontent.com/28887353/27851769-259f673a-6154-11e7-9c04-62f84bb47899.png)

**Comment by DevelopedLogic** [comment]
Intel iMacs' use AMD based graphics, and i've had issue #349 with my computer, which is running on an AMD graphics processor. @dannysmc95  has however told me that he does not get issue #349 on his computer, whether he's referring to his iMac or not i'm not sure.

**Comment by apemanzilla** [comment]
I've had this issue on my Linux system used an AMD R9 390 with open source drivers. (AMDGPU + mesa) Interestingly, this also happens with the new map-style pocket computers, however *only while moving and turning* which causes the pocket computer to rotate - once I stop moving, it returns to normal.

Here's a screenshot of both issues:
![Screenshot](https://i.imgur.com/aSljVqh.png)

**Comment by SquidDev** [comment]
@apemanzilla The pocket computer thing is a CCTweaks feature :p. Though I believe they have the same route cause, just it is much more noticable there.

**Comment by apemanzilla** [comment]
Ah, my bad. I thought it was one of the PRs 😛

**Comment by KnightMiner** [comment]
@SquidDev will it be in a PR? I feel like a lot of CCTweaks could fit in vanilla CC :P

**Comment by apemanzilla** [comment]
I think I've found a possibly related bug. There's a very slight gap between the static monitor texture (the yellow border) and the screen area, which shows the sky behind the block. You can see it if you look closely at the edges near the top right corner of the monitor in [this video](https://zippy.gfycat.com/HelpfulMindlessAnnelida.webm).

**Comment by Lignum** [comment]
> I think I've found a possibly related bug. There's a very slight gap between the static monitor texture (the yellow border) and the screen area, which shows the sky behind the block. You can see it if you look closely at the edges near the top right corner of the monitor in this video.

That's basically always visible, but not really noticeable. I'm guessing it's not really a bug, but just a slight misalignment.

**Comment by BombBloke** [comment]
I believe the display texture is positioned such as to prevent z-fighting with the monitor blocks behind it.
