### ISSUE TITLE
[Suggestion] Command Pocket PCs

### ISSUE THREAD

**Issue by LordMZTE** [dan200/ComputerCraft#306]
it would be cool if you could add a command pocket computer that cann execute the commands a command computer can :D

**Comment by Wojbie** [comment]
What would be use case of that? How would be that different from op in creative spawning and placing one as needed. Cause they can only be used by op in creative.

**Comment by LordMZTE** [comment]
@Wojbie I would use it to create some kind of menu for setting the time in my testing world etc.

**Comment by tomtrein** [comment]
You could always achieve that via the modem API

**Comment by SquidDev** [comment]
Possibly worth noting [this thread](http://www.computercraft.info/forums2/index.php?/topic/22023-). I don't know if Dan's stance has changed since then though.

**Comment by BombBloke** [comment]
I suppose [this one's](http://www.computercraft.info/forums2/index.php?/topic/23292-) also relevant.

**Comment by dan200** [comment]
please keep this issues page for bugs, not feature requests

**Comment by lupus590** [comment]
@dan200 It might be a good idea to point people to the suggestion subforum as well.
