### ISSUE TITLE
Major Window API Bug

### ISSUE THREAD

**Issue by Wojbie** [dan200/ComputerCraft#31]
Reposting from:
http://www.computercraft.info/forums2/index.php?/topic/24449-174-major-window-api-bug/
Tested under pr2 and still valid bug.

**Comment by dan200** [comment]
I think this is fixed. Waiting for the demo program from the original reporter to confirm.

**Comment by Wojbie** [comment]
Top gif one is http://pastebin.com/iv97E9Bb

**Comment by dan200** [comment]
I need the second.

**Comment by Wojbie** [comment]
Recreated second program
http://pastebin.com/3qFT6ysR

**Comment by dan200** [comment]
Cheer.s Confirmed fixed for 1.76pr3
