### ISSUE TITLE
Weird problem with clicking

### ISSUE THREAD

**Issue by KingofGamesYami** [dan200/ComputerCraft#318]
I'm not sure exactly what the issue is and I don't have time to investigate at the moment, but there's something screwy going on with clicks after resizing the minecraft window.

[see here](http://www.computercraft.info/forums2/index.php?/topic/28707-why-cant-click-on-shutdown-not-solved/)

**Comment by SquidDev** [comment]
@KingofGamesYami What version of Minecraft and ComputerCraft? I can't reproduce on the latest version, but I might just be doing something wrong :).

**Comment by Wojbie** [comment]
Could you provide steps or program that reproduces problem?

**Comment by KingofGamesYami** [comment]
I'm using airwaves mods, single player world, advanced computer.  Don't resize the window, try the script (it will work).

Maximize the window, then restore down.  Try the script again (it won't work properly).

**Comment by vpontin** [comment]
Please tell us WHAT MC/FORGE/CC versions you are using.

**Comment by KingofGamesYami** [comment]
My apologies, I haven't had access to the computer with the testing world on it.
1.11.2-forge1.11.2-13.20.0.2228

ComputerCraft-1.80-build from 6/2/2017
luaj-jse-2.0.3 also dated 6/2/2017

These are from [here](https://kaos-network.com/servers/airwaves), assuming the downloads haven't updated since then.

**Comment by KingofGamesYami** [comment]
[Video of glitch](https://github.com/dan200/ComputerCraft/files/1072640/ice_video_20170613-112441.zip)

**Comment by KingofGamesYami** [comment]
Nevermind, I figured it out.  I missed something in the program.
