### ISSUE TITLE
[SMP] Able to crash server with redstone 

### ISSUE THREAD

**Issue by Wojbie** [dan200/ComputerCraft#32]
Reposting:
http://www.computercraft.info/forums2/index.php?/topic/23356-smp-able-to-crash-server-with-redstone/
Prof it still happens:
http://pastebin.com/HyBruP6h
Edit: Sorry i forgot to remove side mods before testing.
Here is clear one. 
http://pastebin.com/pqije6a7

**Comment by dan200** [comment]
Fixed in 1.76pr3. This was a nasty one!
