### ISSUE TITLE
[Bug]write() add 0 to Numbers

### ISSUE THREAD

**Issue by Wilma456** [dan200/ComputerCraft#322]
![write](https://user-images.githubusercontent.com/15185051/27262272-725283c2-5453-11e7-86c7-4cb549dee102.png)

**Comment by SquidDev** [comment]
That's a feature of the Lua REPL. IIRC `write` returns the number of new lines - in this case 0. As lua prints the return value, 10 ends up looking like 100.

**Comment by dan200** [comment]
Yeep. Print does the same thing, but its more clear because that I inserts
a newline and this doesn't

**Comment by Wilma456** [comment]
I had found this while working on #321 and thought, this is a Bug.  Sorry for that.
