### ISSUE TITLE
Add textutils.deserialiseJSON

### ISSUE THREAD

**Issue by Lignum** [dan200/ComputerCraft#323]
Just like how there's a `textutils.serialiseJSON`, it would be useful to have a `textutils.deserialiseJSON`. This would come in handy in use together with the HTTP API, since a lot of web APIs return JSON responses.

**Comment by MineRobber9000** [comment]
You can use JSON APIs for CC. There are many, so I won't link one, but just search "json" on the forums and you'll find some.

**Comment by BombBloke** [comment]
There ARE user-written deserialisers, though to be fair, I haven't found one that works 100%.

It doesn't help that the reason "serialiseJSON" is there in the first place is for Minecraft command support, and some Minecraft commands use a bodgy version of JSON called a "data tag" - the main difference between the two is that JSON requires quotes around key names, and data tags require them to be absent.

textutils.serialiseJSON supports both formats, so it'd be logical that a proper textutils.deserialiseJSON would need to be coded with the same support (were it to be written at all).

**Comment by Janrupf** [comment]
Why not implementing the google json (gson) api. It is able to do things like that.

**Comment by apemanzilla** [comment]
IIRC Minecraft uses gson anyways, so it wouldn't add any extra dependencies.

**Comment by Lignum** [comment]
The problem is that `textutils` is implemented on the Lua side.

**Comment by SquidDev** [comment]
@apemanzilla @Janrupf Sadly even GSON doesn't support the full range of JSON that some Minecraft commands (such as `/entitydata`) generate. Namely the number type suffixes (so `12b` to represent a byte). We'd have to roll our own parser on the Lua side, which is probably the way to go anyway.

**Comment by apemanzilla** [comment]
I think it'd be a better idea to give access to gson methods, and having a separate Lua-side method for using "Minecraft JSON"

**Comment by BombBloke** [comment]
The formats are similar enough that having support for both in the Lua-side API wouldn't require much more code than for just one. So even putting aside the whole "textutils *is* Lua-side" issue, there's not all that much point in using gson for anything if it can't be used for everything.

On the other hand, gson *might* be able to handle everything. [Gamepedia reckons](https://minecraft.gamepedia.com/Commands#Data_tags) data tags are "a [lenient](https://static.javadoc.io/com.google.code.gson/gson/2.8.0/com/google/gson/stream/JsonReader.html#setLenient-boolean-) form of JSON", but the method linked indeed doesn't claim to handle the suffixes SquidDev mentioned, so it may well just be wrong about that.

**Comment by apemanzilla** [comment]
I wouldn't be surprised if it could, Gson is very powerful and very customizable.

**Comment by dan200** [comment]
If somebody writes a good version of this and PR's it, i'll probably merge it.
