### ISSUE TITLE
rghtCtrl key code differen from keys.rightCtrl?

### ISSUE THREAD

**Issue by Wojbie** [dan200/ComputerCraft#33]
There is bug report:
http://www.computercraft.info/forums2/index.php?/topic/21188-cc165smpssp-invalid-value-in-keysrightctrl/
Hoover when testing in latest cc error seems to be opposite for me and Bomb Blocke like in the post.
Is it some weird keyboard magic OR real issue?

**Comment by dan200** [comment]
The key codes are based on the Minecraft/lwjgl key codes here: http://minecraft.gamepedia.com/Key_codes
If they're incorrect, it's an LWJGL bug.

**Comment by Wojbie** [comment]
So according to that page rightCtrl is 157 like for me and Bomb bloke.
But keys.rightCtrl reports 153
So keys.rightCtrl is set wrong then?

**Comment by Wojbie** [comment]
http://imgur.com/0gwEHXz

**Comment by dan200** [comment]
You're right, the original bug was incorrectly reported. FIxing the actual bug now.

**Comment by dan200** [comment]
Fixed for 1.76pr3
Fun fact: this bug was 4 years old!

**Comment by Wojbie** [comment]
Yea i may be dumpster diving in bug report forums and picking up still valid ones ;D Hope you don;t mind.
