### ISSUE TITLE
Wierd jumpiness of modems and turtles when water is dissapering.

### ISSUE THREAD

**Issue by Wojbie** [dan200/ComputerCraft#34]
No idea how to explain to so here are 2 gifs.
Modem and turtle dance party?
If you place wireless modems (both types) and turtles.
Make a large stream of water going downwards and then break source block.
Disappearing water will cause turtles to blink and modems to act like (trap)doors.
It appears to be purely graphical.
First is in ssp 2nd in smp.
http://gfycat.com/WholeRealBaldeagle
http://gfycat.com/WearyCautiousBufeo

**Comment by dan200** [comment]
Weird! This seems to be caused by minecraft for some reason not having the proper TileEntities available during rendering. Not a lot I can do about that, but I've managed to make modems at least handle this case with a bit more grace.
