### ISSUE TITLE
turtle.suck() and turtle.drop() give incorrect return values when an inventory is full

### ISSUE THREAD

**Issue by Twijn** [dan200/ComputerCraft#340]
turtle.drop(), turtle.dropUp(), turtle.dropDown(), turtle.suck(), turtle.suckDown(), and turtle.suckUp() will sometimes give incorrect return values when putting items into an inventory.

- Inserting X into an item full of Y will result in "false, No space for items" (Expected)
- Inserting X into an item full of X will result in "true" (Unexpected) (No items were moved)

This appears to be the same for both turtle.suck() and turtle.drop().

**Comment by KingofGamesYami** [comment]
Looked into this one, not sure why it's happening.  [There appears to be code covering this situation](https://github.com/dan200/ComputerCraft/blob/master/src/main/java/dan200/computercraft/shared/turtle/core/TurtleDropCommand.java#L74), but I can confirm that it does return true.  I speculate the comparison is not valid, and `ItemStack.areItemStacksEqual` be used to attempt a patch.  I don't have CC setup for development right now, or I would try this.

**Comment by SquidDev** [comment]
@KingofGamesYami is correct - some implementations of `IItemHandler.insertItem` (such as `InvWrapper`'s (and other capabilities) will clone the item stack, meaning they are not the same object. It'd probably be better to use `InventoryUtil.areItemsEqual`, but otherwise the suggested fix should work correctly :)

**Comment by Twijn** [comment]
I looked at it a bit as well before posting the issue, though did not attempt to edit it or create a PR due to my pure inexperience and lack of a CC development setup, similarly to @KingofGamesYami , though I would think that comparing only the amounts of both ItemStack's would be ample - checking if the materials or data is equivalent is irrelevant.
