### ISSUE TITLE
bg.lua erroring out

### ISSUE THREAD

**Issue by DevelopedLogic** [dan200/ComputerCraft#352]
![image](https://user-images.githubusercontent.com/28887353/27851573-510dbd28-6153-11e7-8520-6d6f9316e14c.png)
this is my startup script:
![image](https://user-images.githubusercontent.com/28887353/27851594-61da43f6-6153-11e7-8310-1797702bbffa.png)
Happens on more than one computer running two different programs under BG

**Comment by SquidDev** [comment]
`multishell.launch` is [checking against `tProgramArgs` rather than `tProgramEnv`](https://github.com/dan200/ComputerCraft/blob/master/src/main/resources/assets/computercraft/lua/rom/programs/advanced/multishell.lua#L213). @Wilma456, could you fix this?

**Comment by Wilma456** [comment]
Copy and Paste error. Sorry for that.
