### ISSUE TITLE
[Suggestion] Get another computer's label the same way you get its ID

### ISSUE THREAD

**Issue by Wyvern67** [dan200/ComputerCraft#359]
It's all in the title

It would be pretty cool if you could read another computer's label the same way you can currently read their ID.

**Comment by lupus590** [comment]
Or you could implement a way to transmit the label via rednet.

**Comment by BombBloke** [comment]
If you want to find a computer with a specific label, [rednet.lookup()](http://www.computercraft.info/wiki/Rednet.lookup) can already help you with that.

If you just want a list of all computer labels in the area, that's a different story - although I'm not sure what use such a list would be, if they systems on it are not specifically coded to accept incoming connections from your script anyways.

**Comment by SquidDev** [comment]
I'm presuming this is actually talking about a `.getLabel()` method on a [computer peripheral](http://www.computercraft.info/wiki/Computer_%28API%29) - which would be a useful feature. Sure, it could be transmitted via rednet, but that isn't a reason to not have it :).

If I'm totally misunderstanding the OP, then ignore me - sorry :).

**Comment by Wyvern67** [comment]
Yep, that's what I was suggesting, SquidDev. You got it right. I was
getting upset that no one was understanding, thanks for reading carefully.

The thing is, to use rednet, you need a modem. You don't need a modem to
use computer.getID(), just to be in the adjacent block.
