### ISSUE TITLE
[Suggestion] Alternative mouse_drag -> mouse_pull

### ISSUE THREAD

**Issue by DevelopedLogic** [dan200/ComputerCraft#361]
My idea is for a new event to be implemented, mouse_pull.
This event would fire once the user has dragged and then let go of the mouse.

It will return the startx, starty, endx and endy pos, where the mouse was clicked, and where it was let go.

This would make window interactions easier for OSes which have movable windows. I'd also like to implement it into my own OS.

**Comment by BombBloke** [comment]
You'd still need to pull mouse_drag events to follow the progress of dragged elements around the screen, and we've already got mouse_up firing when a button is released, so another event would simply be reiterating data, yeah?

**Comment by DevelopedLogic** [comment]
:/
