### ISSUE TITLE
[SUGGESTION] Get interacting player's nickname or UUID

### ISSUE THREAD

**Issue by manu-03** [dan200/ComputerCraft#366]
In order to add more security and customisation posibilities, there would be great to get the player's name in "mouse_click", "mouse_up", "key_down", "key_up", "monitor_touch" and so on, as the last parameter.

**Comment by KnightMiner** [comment]
I feel like while this is useful, it starts to break immersion. Your real life computer does not know it's you typing on the keyboard.

I can see this being added as some sort of "retinal scanner" peripheral, but I'm not sure it fits in vanilla ComputerCraft.

**Comment by dan200** [comment]
please keep this issues page for bugs, not feature requests

**Comment by lupus590** [comment]
@dan200 You may want to say that on the readme, or you may want an issue template (and maybe other [special github files](https://github.com/kmindi/special-files-in-repository-root#platform-dependent-featurestemplates)).
