### ISSUE TITLE
Worm program flickers nil in place of score when running on a monitor

### ISSUE THREAD

**Issue by apemanzilla** [dan200/ComputerCraft#368]
I had noticed this a while ago working on CCEmuX, but hadn't been able to reproduce it in CC. I noticed today that it only happens on monitors - not computers, turtles, or pocket computers. A picture is worth a thousand words, so [here's a short video of the issue](https://zippy.gfycat.com/HelpfulMindlessAnnelida.webm).

I've quickly skimmed over the source for worm, but haven't seen anything obvious yet.

**Comment by BombBloke** [comment]
That'd be [this line here](https://github.com/dan200/ComputerCraft/blob/f5edb32be9756bae0a856cfc7409e0b29d211dfd/src/main/resources/assets/computercraft/lua/rom/programs/fun/worm.lua#L141), presumably used for debugging purposes and then never disabled.
