### ISSUE TITLE
Numerous issues with non-ascii characters

### ISSUE THREAD

**Issue by dan200** [dan200/ComputerCraft#37]
Feel free to speculate about why i'm logging this bug!

**Comment by AEnterprise** [comment]
forge is working on a renderer for non-ascii characters on a seperate branch, you might wana take a look there or ask them if it will be merged to the master branch soon

**Comment by SquidDev** [comment]
String Bug? Is there a way to fix this without passing `byte[]` everywhere?

**Comment by dan200** [comment]
Solved in 1.76pr3 :smile:
