### ISSUE TITLE
[Suggestion]Make fs.isReadOnly() check for FilePermission

### ISSUE THREAD

**Issue by Wilma456** [dan200/ComputerCraft#370]
If you don't have write access to a file on your Computer, fs.isReadOnly should return false.

**Comment by Wojbie** [comment]
What exactly you have in mind when you say - no write access?

**Comment by Wilma456** [comment]
chmod u-w Filename

**Comment by CrazedProgrammer** [comment]
@Wojbie What he means is when a file is marked as read-only for the current user i.e. the user cannot write to the file.

**Comment by Wojbie** [comment]
Are we speaking about single player setup then? I would find it weird for there to be file not belonging to server running server user.

Anyhow now that exact problem has been explained I agree. This is rather weird edge case but is should be fixable.

**Comment by MineRobber9000** [comment]
@Wilma456 I believe you mean `true` -- that's what `fs.isReadOnly` returns for read-only files (no write access)

**Comment by dan200** [comment]
CC (like Minecraft itself), relies on you having write access to your save directory. much more than this method would break if that were not the case!
