### ISSUE TITLE
Command Computer results being translated

### ISSUE THREAD

**Issue by dirk1763** [dan200/ComputerCraft#38]
If a command of a command computer fails there is currently no way of knowing why it failed since the error message is in the language of the player (or the server). There is no way a command computer program can check for a spezific errormessage in every language minecraft offers. Most of the languages are not even printable (e.g. german because of äüö).

Please make commands return the untranslated string. So that an lua program written on an english server does still work on a german server and vice versa.

Steps to reproduce:
-Turn language of the server to spanish, swedish, german or chinesse.
-run the lua program
-enter: commands.entitydate("@e","{}")

In pr2 it crashes because of the window api, in pr3 it probatly wont, but it is still not comparable and therefore not useful.

The only thing that can be done with an translated string is outputing it to the minecraft chat, but with the tellraw command a string can be translated as well.

**Comment by dan200** [comment]
The crashes have been fixed. I won't be changing to unlocalised strings though, as it's much less usable for lot's of use cases. If it helps: know that dedicated servers will always use english text.

**Comment by Lion4ever** [comment]
Since we have all characters of most european languages now, can we get a textutils.translate function?
that would not only allow user programs to show the normal names for turtle items and gui buttons in the users language, but it would help finding out why the command computer failed as well.
