### ISSUE TITLE
[Bug]Edit ignore space limit

### ISSUE THREAD

**Issue by Wilma456** [dan200/ComputerCraft#385]
As you will see from the attached gif, edit ignore the space limit.

![space](https://user-images.githubusercontent.com/15185051/28633944-c9b2082c-7235-11e7-8266-e97087f7ec6d.gif)

**Comment by SquidDev** [comment]
When ComputerCraft calculates the amount of space each file takes, it assumes a [minimum file size of 500 bytes](https://github.com/dan200/ComputerCraft/blob/master/src/main/java/dan200/computercraft/core/filesystem/FileMount.java#L387). This prevents people creating millions of empty files which, even though they are empty, would still take up some space on the physical disk. Consequently, there is no difference in "size" between an empty file, one with 200 characters in and one with 500 characters in.

That's what you're seeing here: the file you're testing with is less than 500 characters and so adding several more doesn't make any difference to the disk usage. If you go over 500 characters, *then* your file will be truncated.

**Comment by Wojbie** [comment]
What you show us seems to point to fs.open allowing to save file over the size limit if file already exists and it's been overwritten? Could someone test that with larger size difference then few bytes?

**Comment by Wilma456** [comment]
@SquidDev Thank you for explaining
