### ISSUE TITLE
Character 127 and 255 renders as ?

### ISSUE THREAD

**Issue by Cruor** [dan200/ComputerCraft#40]
![Image](https://dl.dropboxusercontent.com/u/23386746/ShareX/2015/12/11/23-47-36.png)

**Comment by dan200** [comment]
127 is an unassigned character, so I left it as ? in the font.
Just fixed the bug with 255, was a ">= 255" that should of been a "> 255"

**Comment by BombBloke** [comment]
Character Map in Windows tells me 127 should be a "non-breaking space", that is, a space which prevents a line break. Leaving it blank may be more suitable than ?.

**Comment by dan200** [comment]
non breaking space is unicode char 160, 127 is the "delete" control
character.

**Comment by BombBloke** [comment]
Ah, you're right, I misreading things.
