### ISSUE TITLE
backport if to Minecraft 1.7.10

### ISSUE THREAD

**Issue by veso266** [dan200/ComputerCraft#403]
Hi I would like to know if anyone can backport ComputerCraft to minecraft 1.7.10 because I love to play it on Tekkit-Legends but its only for Minecraft 1.7.10 so and the I am stuck using ComputerCraft 1.75 but would love to use the latest version on Tekkit-Legends

Thanks for Anwsering and Best Regards

**Comment by SquidDev** [comment]
It might be better to add your voice to #226 instead - it'd be much easier to backport features to 1.7.10 if the source code is available. 

That being said, I'm looking at the Tekkit legends mod list and I'm pretty sure most of those mods have been updated to 1.11.2 (or 1.12), or there is an equivalent mod around. It would probably be better to recreate Tekkit Legends in a more recent version of Minecraft, that way you get the latest features from *all* the mods.

**Comment by lupus590** [comment]
>It would probably be more desirable to recreate Tekkit Legends in a more recent version of Minecraft, that way you get the latest features from all the mods.

And the latest features of vanilla.

**Comment by veso266** [comment]
> It would probably be more desirable to recreate Tekkit Legends in a more recent version of Minecraft, that way you get the latest features from all the mods.

well that would be great but Tekkit-Legends has a lot of mods some of them like Ender Storage: https://mods.curse.com/mc-mods/minecraft/229306-ender-storage or Blue Power (any alternative that would loke and behave the same as Red Power?) that are only available for Minecraft 1.7.10 or some of them like Buildcraft that are unstable at the moment

**Comment by SquidDev** [comment]
I've put together a list of mods which have changed and their "modern" replacements:

| Original       | Replacement                                                              |
|----------------|--------------------------------------------------------------------------|
| AOBD           | Hasn't been ported, but [B.A.S.E][base] seems a good replacement.        |
| Big reactors   | [Extreme  reactors][extreme-reactors]                                    |
| BluePower      | [Teckle] for pipes. [ProjectRed][project-red] has been ported to 1.10, but not 1.11.2 |
| BuildCraft     | Updated to 1.11.2, but not 1.10.2. Still in beta though.                 |
| Logistic Pipes | Sadly not updated                                                        |
| Carpenter's Blocks | There's [this][master-blocks], or Chisel and Bits                    |
| EnderStorage   | [EnderThing][enderthing]                                                 |
| Industrial Craft | IC2 has been updated to 1.11.2, IC2 Classic is only 1.10.2             |
| IC2 Nuclear Control | There's [World Control][world-control] for 1.10.2                   |
| JABBA          | [Storage Drawers][storage]                                               |
| NEI            | Exists as an addon to JEI                                                |
| OpenCCSensors  | Not updated. If someone really wants it though, I'm happy to port it.    |
| Power Converters | [Energy Converters][energy-conv]                                       |
| QuiverBow      | Not updated.                                                             |
| Railcraft      | Updated to 1.10.2, not 1.11.2.                                           |
| Remain in Motion | [Funky Locomotion][funk-loc]                                           |
| Solar Flux     | [Solar Flux Reborn][sfb]                                                 |
| Modular Power Suits | Not updated                                                         |
| Waila          | [The One Probe][top] or [Fruit Phone][fp]                                |

I realise it's far from ideal, but sadly it isn't really practical to keep supporting previous versions of Minecraft. After all, 1.7.10 is now three years old.

[base]: https://minecraft.curseforge.com/projects/b-a-s-e
[extreme-reactors]: https://minecraft.curseforge.com/projects/extreme-reactors
[teckle]: https://github.com/elytra/Teckle/releases
[project-red]: https://minecraft.curseforge.com/projects/project-red-base
[master-blocks]: https://minecraft.curseforge.com/projects/master-blocks-mod
[enderthing]: https://minecraft.curseforge.com/projects/enderthing
[world-control]: https://minecraft.curseforge.com/projects/world-control
[storage]: https://minecraft.curseforge.com/projects/storage-drawers
[energy-conv]: https://minecraft.curseforge.com/projects/energy-converters
[funk-loc]: https://minecraft.curseforge.com/projects/funky-locomotion
[sfb]: https://minecraft.curseforge.com/projects/solar-flux-reborn
[top]: https://minecraft.curseforge.com/projects/the-one-probe
[fp]: https://github.com/elytra/FruitPhone/releases

**Comment by KnightMiner** [comment]
There actually was a ported version of ender storage. There's also quite a few new mods worth trying which you may be more likely to use if you no longer have some of the old options

**Comment by veso266** [comment]
@SquidDev Thanks for this list OpenCCSensors would be realy great if you could port it to newer Minecraft before it dies completly and then nobody want to port it anymore

would like to ask why would be dificult to port CC to Minecraft 1.7.10 I am not a JAVA coder myself and don't never realy understood why every new Minecraft version requires mod to be ether completly rewritten or updated (isn't this FML and LiteLoder job to deal with Minecraft Updates? and then develop mods on top of their APIS?)

for now I am stying on MC 1.7.10 until Tekkit-Legends (Revised) comes along (would still love to see ComputerCraft for Minecraft 1.7.10), (wondering how OpenComputers still has the latest version for Minecraft 1.7.10

because of all that mod changing Tekkit has a lot of varients (Tekkit Classic (MC 1.2.5), Tekkit Lite (MC 1.4.7) (last version with RedPower (what is the latest closest alternative for it (heard that ProjectRed is going in its own direction? and BluePower is sadly not updated anymore), Tekkit-Legends (MC 1.7.10), Tekkit (never understood this one)

**Comment by SquidDev** [comment]
> I don't never really understood why every new Minecraft version requires mod to be ether completely rewritten or updated

Pretty much every time Minecraft updates, Mojang will change some the game's internals. Sometimes these changes are relatively small (such as 1.10.2 -> 1.11.2), but sometimes they require massive restructuring of code. 1.7.10 to 1.8.9 is a great example of this: pretty much the entire rendering system was changed, which meant every mod had to change with it, causing a lot of work for modders. This is one of the reasons that many mods didn't make it past 1.7.10.

Forge (of which FML is a part) doesn't really aim to preserve compatibility between Minecraft versions. It instead focuses more on compatibility between mods, making sure multiple mods can be run at once and don't mess with each other. I'd argue this is the correct stance to take, as maintaining compatibility throughout all the changes Minecraft has made would be very hard. However, it does create a reasonable amount of work between versions.

> Would like to ask why would be difficult to port CC to Minecraft 1.7.10

Part of the issue is that the source code is not available, hence #226. If one has the code, it isn't too difficult, it's just a bit of a faff - each version you maintain adds a little bit more complexity, and one more thing to test. I may be a little biased though, as I'm one of the "always use the latest version" people :).

**Comment by dan200** [comment]
Nope. We don't backport, the versions of CC released for 1.7.10 work fine
