### ISSUE TITLE
(Suggestion) Please make CC work for 1.10.2

### ISSUE THREAD

**Issue by koolkid293** [dan200/ComputerCraft#406]

**Comment by SquidDev** [comment]
Whilst there hasn't been a stable release yet, CC has worked on 1.10.2 for about three months. You can download a development build [from here](https://cc.crzd.me).

**Comment by lupus590** [comment]
Perhaps that link should be on the read me.

**Comment by SquidDev** [comment]
@lupus590 IMO it would be better to have another beta release - whilst the build server is nice to have, it isn't "official", and isn't ever going to be as prominent as something on CurseForge.

**Comment by lupus590** [comment]
@SquidDev  True, but a link might be helpful to those who don't know about it. (That said, those who don't know of it may not be able to navigate the website).

**Comment by vpontin** [comment]
I would love to hear @dan200 's instance about that (another CF release)

**Comment by dan200** [comment]
Done
