### ISSUE TITLE
Why is localhost on the blacklist?

### ISSUE THREAD

**Issue by Wilma456** [dan200/ComputerCraft#418]
What is the reason, why localhost is on the blacklist?

**Comment by redfast00** [comment]
What blacklist? The HTTP or the rednet one?

**Comment by Wojbie** [comment]
#170 should explain it.

**Comment by apemanzilla** [comment]
Basically, since CC runs on the server, any requests look like they come from the server rather than the client controlling the CC computer. This could alloy people to get around firewalls and access internal services, which is a security risk.

**Comment by Wilma456** [comment]
Thank you
