### ISSUE TITLE
Palette Color change in Paint?

### ISSUE THREAD

**Issue by PixelFox1** [dan200/ComputerCraft#420]
Now, this is more of a request than an issue, but some way (e.x. middle clicking) to change the actual palette for the color in the default paint program? (Or has this already been added and I just didn't know?)

**Comment by KingofGamesYami** [comment]
IIRC the program does not change the pallette, so changes made before it's executed will stick.  However, there does not exist any storing of palettes in the actual file produced (nor should there be).

**Comment by PixelFox1** [comment]
Yes, I'm saying it should.

Why do you think there shouldn't be?

**Comment by KingofGamesYami** [comment]
Because palette changes affect the entire screen, not just the image you drew.

**Comment by PixelFox1** [comment]
Of course it does. I'm just saying it would be nice to get a feel for palette on the screen, correct colors, etc, so you can change the palette while editing the picture. Whatever, I'll just make it.

**Comment by KnightMiner** [comment]
I feel this would actually be worth writing as your own program, make a second paint format which stores a pallete in addition to the pixels.
