### ISSUE TITLE
Signs n Turtles

### ISSUE THREAD

**Issue by dirk1763** [dan200/ComputerCraft#43]
The turtle.place("text") function crashes the game because signs are like tellraw/books now.

I beg you, please let us be able to make colorful signs with the turtles :pray:

**Comment by apemanzilla** [comment]
Just want to say, it was possible to make colored/formatted signs before with the section symbol (§) because you could add it with an external editor, then run it on CC.

**Comment by dan200** [comment]
Crash fixed in 1.76pr4.
