### ISSUE TITLE
[Suggestion] Crafty turtles with items not part of recipe in inventory

### ISSUE THREAD

**Issue by redfast00** [dan200/ComputerCraft#432]
Currently, when you want to craft items with a Crafty turtle, the turtle cannot have any items that are not part of the recipe in its inventory (see [the wiki](http://computercraft.info/wiki/Turtle.craft)) It would be really cool if a Crafty turtle could use some slots as "scratch space" (I suggest slots 4, 8, 12 and 13-16). There slots wouldn't be part of the recipe and the other slots form a 3x3 area which could contain the area for recipes like in a crafting table.

**Comment by dan200** [comment]
The crafty turtle treats the whole inventory as a crafting table. This is the intended design (and to change that would break things and confuse people)

**Comment by lupus590** [comment]
@dan200 out of curiosity, why is it intended this way?

**Comment by redfast00** [comment]
@dan200: why is this the intended way? Are there secret 4x4 recipes? Would it be okay to add an (optional) parameter to turtle.craft that selects the size of the grid? This wouldn't break old software, but allows new versions to restrict to a 3x3 grid.

**Comment by Lignum** [comment]
I would guess this is because turtles used to have 3x3 inventories.

**Comment by redfast00** [comment]
That does seem logical, but I feel this should still be changed since it would benefit users. For example: I have a Computercraft automated goldfarm. I'd like to compress the gold down to gold blocks. If I want to do this with the current implementation, the turtle needs to turn a lot to reach into the different chests and lava. If only there were some 'scratch space' in the turtles inventory...
