### ISSUE TITLE
[1.76pr3] Left curly brackets have an extra pixel

### ISSUE THREAD

**Issue by KnightMiner** [dan200/ComputerCraft#44]
![2015-12-11_19 01 01](https://cloud.githubusercontent.com/assets/12155288/11759088/8571b1dc-a039-11e5-9a10-ab947d5fa2a6.png)

Title says all, there is an extra pixel in all left curly brackets, but not the right ones, which looks very funny and is really messing with me. (I think everyone else took all the good bugs...)

**Comment by dan200** [comment]
Fixed for 1.76pr4. Thanks!
