### ISSUE TITLE
[1.76pr2-3] Edit script: Incorrect text colouration

### ISSUE THREAD

**Issue by BombBloke** [dan200/ComputerCraft#46]
Strings (and the quotes around them) should be rendered in red, but empty strings may confuse the parser as pictured.

![2015-12-12_12 21 38](https://cloud.githubusercontent.com/assets/12162603/11759252/0c4beb82-a0cb-11e5-96bd-d5ffafd98ba6.png)

**Comment by oddstr13** [comment]
hah, exactly like the Python syntax highlighting in nano :D

**Comment by dirk1763** [comment]
Happens with zero length strings (because of [^\\]) and with multiline strings using [[

![string color](https://cloud.githubusercontent.com/assets/8234006/11762151/8f4614f0-a0de-11e5-88ce-1641f194688f.PNG)

**Comment by dan200** [comment]
Empty quotes fixed for pr4. Multiline quotes unlikely to be fixed due to the complexity it would add to the edit program.
