### ISSUE TITLE
Problem when erroring öäü§....

### ISSUE THREAD

**Issue by Luca0208** [dan200/ComputerCraft#47]
If you open a lua prompt and do "error("ö")" it will result into some weird chars.
Anavrins told me that everything that has a higer byte value than 127 does that.
![2015-12-12_07 12 09](https://cloud.githubusercontent.com/assets/9638292/11760538/b8e7cff4-a09f-11e5-8036-73ff99b7c2e3.png)

**Comment by dan200** [comment]
Fixed in 1.76pr4
