### ISSUE TITLE
[1.12.1] Parsing error

### ISSUE THREAD

**Issue by UnPure** [dan200/ComputerCraft#471]
On server startup, ComputerCraft is producing this error
https://pastebin.com/uyYwp97g

The full log is here: https://pastebin.com/5EJME00p

ComputerCraft: 1.80pr1
Forge: 14.22.0.2475

**Comment by SquidDev** [comment]
The fact that similar errors are occurring for `minecraft:recipes/food/pumpkin_pie`, `minecraft:recipes/food/mushroom_stew` and several more makes me pretty sure this isn't a ComputerCraft bug - especially as I'm not getting such errors with ComputerCraft on its own.
