### ISSUE TITLE
Paintutils not working

### ISSUE THREAD

**Issue by pgr4567** [dan200/ComputerCraft#478]
On CraftOS paintutils.drawImage(image,1,1) isn´t working ---> expected table, got nil
![image](https://user-images.githubusercontent.com/32647406/31348751-ff3cf242-ad20-11e7-8d0e-e17f8c527d5b.png)
Code:
![image](https://user-images.githubusercontent.com/32647406/31348807-264ad426-ad21-11e7-94d5-3ca39d2238a8.png)

**Comment by SquidDev** [comment]
This was fixed in #441. Whilst there hasn't been a new release, you can [download a development build](https://cc.crzd.me/).

**Comment by pgr4567** [comment]
Thx :D
