### ISSUE TITLE
Turtles render infront of hand held slimeblocks

### ISSUE THREAD

**Issue by dirk1763** [dan200/ComputerCraft#48]
![covered](https://cloud.githubusercontent.com/assets/8234006/11762267/960c491a-a0e0-11e5-9a72-e9604ff4b6e3.PNG)
turtle is behind the armorstand not infront of it:
![uncovered](https://cloud.githubusercontent.com/assets/8234006/11762269/b986ad40-a0e0-11e5-9616-50f4fd852fdf.PNG)

Same happens when the slimeblock is in a players hand, so it has nothing to do with the armorstand
![heldbyme](https://cloud.githubusercontent.com/assets/8234006/11762270/d5496e78-a0e0-11e5-9cc8-0a4271586df7.PNG)

**Comment by dirk1763** [comment]
through a slime block item they are not rendered at all:
![there](https://cloud.githubusercontent.com/assets/8234006/11762342/89e6bef6-a0e3-11e5-9b7e-8be9235ee0a2.PNG)
![notthere](https://cloud.githubusercontent.com/assets/8234006/11762344/8c1fbd44-a0e3-11e5-9f0f-c75ccc65e133.PNG)
This helps testing:
/entitydata @e[type=Item] {PickupDelay:32767}

**Comment by KnightMiner** [comment]
The second issue is [MC-35920](https://bugs.mojang.com/browse/MC-35920) (also affects chests and signs, but the topic does not state that yet). I doubt there is much Dan can do to fix that.

The first issue I have not see anywhere in vanilla, though [similar issues exist](https://bugs.mojang.com/browse/MC-9553)

**Comment by dan200** [comment]
Just tested this, was able to reproduce both problems with Turtles, Chests and Signs.
KnightMiner is right: this is due to the order that Vanilla sorts entities for rendering. 1.8 takes most rendering code out of the modders hands, so there's nothing I can do about this.
