### ISSUE TITLE
Issues and License on CF are not the same as on Github

### ISSUE THREAD

**Issue by C0rn3j** [dan200/ComputerCraft#484]
Curseforge page is missing the issues tab - it should link to Issues here. https://minecraft.curseforge.com/projects/computercraft

---

Also the License is set as All rights reserved, but you are using some custom license. based on the MPL - May I know why you chose MPL, and on top of that you customized it(I didn't look exactly how)?

It seems like the well-established GPL but with added stupid clauses like this one 

"The present license is granted to any user of the mod. As a prerequisite, 
a user must own a legally acquired copy of Minecraft"

and this one 

"the code and assets may not be used in commercial mods, mods for other
games, other games, other non-game projects, or any commercial projects."

**Comment by dan200** [comment]
The link on curseforge have been updated
