### ISSUE TITLE
Config Comments can't translatet with a lang file

### ISSUE THREAD

**Issue by Wilma456** [dan200/ComputerCraft#489]
If you look  at the [preInt](https://github.com/dan200/ComputerCraft/blob/19e4c03d3a83e7367696937b7a702246490acca0/src/main/java/dan200/computercraft/ComputerCraft.java#L263) you will see, that the Comments for the Config are set in the code, what means they can't be translated by a lang file.

**Comment by SquidDev** [comment]
Sadly this is a limitation/side effect of using Forge's config system. As comments are also saved to a file, they have to be a constant string rather relying on resource packs. 

It would be *technically* feasible to listen to language/resource pack changes and update the comments, but it's a massive hack and I'm not convinced it's worth it.

**Comment by lupus590** [comment]
Providing translations via a wiki would be possible, that way people can look up a translated version of the config file and cross-reference with their one to find where they want to make changes.

**Comment by Lignum** [comment]
Isn't Forge's new mod config screen localisable?

**Comment by SquidDev** [comment]
@Lignum Only the names of the comments (which is what [you see here](https://github.com/dan200/ComputerCraft/blob/master/src/main/resources/assets/computercraft/lang/en_us.lang#L45-L64)). The comments themselves are not localised. Given that the names are pretty descriptive by themselves I don't think we need to worry too much.

**Comment by Lignum** [comment]
> Given that the names are pretty descriptive by themselves I don't think we need to worry too much (says the native English speaker).

I concur, most people who play Minecraft, especially modded, will have decent enough English skills to be able to understand the config file at the very least.

Honestly, I wouldn't worry about this at all, unless it becomes evident that this is in fact a real problem, in which case we could simplify the descriptions a little bit. But really, this issue isn't specific to us, if you play modded Minecraft, you're basically expected to be able to speak at least half-decent English.

If we wanted to fix this, the Forge team would need to do something about it, not us.
