### ISSUE TITLE
paintutils.lua:38: attempt to call nil

### ISSUE THREAD

**Issue by RGFTheCoder** [dan200/ComputerCraft#500]
`paintutils.lua:38: attempt to call nil`
I get this error after downloading and compiling source
All "GUIs"/"OSes" just crash immediately or after setup

**Comment by SquidDev** [comment]
Duplicate of #478: this was fixed in #441. Whilst there hasn't been a new release, you can [download a development build](https://cc.crzd.me/).

**Comment by RGFTheCoder** [comment]
I built it and it didn't work
I did `gradlew build`
I had to download **All The Mods 3** and get the jar
I just checked and the dev build has a org folder in the jar and I don't know why it won't be there when I build it

**Comment by SquidDev** [comment]
LuaJ isn't packaged when using Gradle: you'll need to run `./deploy.sh` (on a Linux/Mac sadly) in order for this to work. There's a PR to simplify it but it hasn't been merged yet. 

Yep, it's a bit of a pain - there's a reason we run a download server :).

**Comment by RGFTheCoder** [comment]
but if I modify it how can I send it to my friends?

**Comment by RGFTheCoder** [comment]
whoops

**Comment by RGFTheCoder** [comment]
is there a way to deploy it with the org folder

**Comment by SquidDev** [comment]
You could open the produced jar with an archive tool (7zip, etc...) and copy the org folder across. That should be sufficient.

**Comment by RGFTheCoder** [comment]
thx
