### ISSUE TITLE
[1.12] Mod doesn't work after using mklink

### ISSUE THREAD

**Issue by OrdinaryCassetteNerd** [dan200/ComputerCraft#501]
In order to move Minecraft from 1 partition of my HDD to another, I had to use mklink /J, else it would default to %appdata%\.minecraft. Problem is, after doing this and installing Forge 1.12, the mod doesn't load! Please help!

**Comment by SquidDev** [comment]
This will either be a problem with your setup or Forge.

Using symlinks within Minecraft is a little dodgy. Instead, it should be possible to configure the location Minecraft installs to inside the vanilla launcher. You might also want to look into [MultiMC](https://multimc.org/): it's an alternative Minecraft launcher which makes it easier to manage multiple versions/instances of Minecraft.

**Comment by OrdinaryCassetteNerd** [comment]
But I use cracked Minecraft!

P. S. I have found out the possible reason: I'm using an old folder on the new partition, where I miserably failed with mklink.

**Comment by OrdinaryCassetteNerd** [comment]
Yeah, it ended up being the reason. The MC launcher was using F:\Minecraft (where I made a fail with mklink). I set it to the default and it works, bro!

**Comment by SquidDev** [comment]
> But I use cracked Minecraft!

Worth noting that this [violates ComputerCraft's license](https://github.com/dan200/ComputerCraft/blob/master/LICENSE#L29-L30). Honestly, just buy the game - I know it's a commitment but in the long term it's not that expensive and definitely worth it.

**Comment by OrdinaryCassetteNerd** [comment]
If at least I could afford it.. I would LOVE that!

**Comment by OrdinaryCassetteNerd** [comment]
Oh, and I shall NOT forget credit card issues!

**Comment by vpontin** [comment]
Its depends of what cracked launchers you use. I will obviously not name them, but there are some will operate like the vanilla "legacy" launcher which have the Profiles working normally, so this isnt a excuse.

But like Squid said, its a grave offence to seek help in modding community using pirated Minecraft (if you dare to post this on Minecraft Forge forums you'll get an instant ban).

And finally about "credit card issues" (i dunno what you mean, just bought my account via this method without issues), you could try buying Minecraft using a gift card (some stores around the world have them): http://lmgtfy.com/?q=gift+card+minecraft

**Comment by OrdinaryCassetteNerd** [comment]
What about https://en.wikipedia.org/wiki/Croatia ?

**Comment by OrdinaryCassetteNerd** [comment]
Also, my cracked launcher is TeamExtreme (without Premium Mode).

**Comment by apemanzilla** [comment]
This isn't really the place to be discussing, let alone advertising cracked Minecraft launchers.

**Comment by Selim042** [comment]
Hey, guess what? Christmas is coming up! Why not ask for it as a gift? It isn't that expensive and shouldn't break many gift-givers' budgets!

**Comment by OrdinaryCassetteNerd** [comment]
But everyone I know who can afford a gift card doesn't know WTF Minecraft or a gift card is and/or nobody wants to spend a s*** on one! And there are no Minecraft gift cards in Croazia...

**Comment by lupus590** [comment]
Give them a link to an international website which will ship to your country, don't try to explain what it is unless they ask, and just say "I want this for Christmas".

**Comment by OrdinaryCassetteNerd** [comment]
Pfft, they are ALL afraid of Internet shopping!

**Comment by lupus590** [comment]
Is buying it yourself an option? Could you guide one of them through it?

**Comment by Selim042** [comment]
None of these are valid excuses to pirate a game.

**Comment by vpontin** [comment]
I hope @dan200 or other with admin privileges could lock this sick "issue". OP tries to make illegal things and fails. Period.

**Comment by OrdinaryCassetteNerd** [comment]
Same.
