### ISSUE TITLE
Typo in rednet api. Cannot use it

### ISSUE THREAD

**Issue by RedGalaxySoftware** [dan200/ComputerCraft#505]
Hi,
I found a typo in the rednet api (1.12 beta) definition on line 116: `type( nTimeoutl )` (extra 'l' after 'nTimeout')... This causes an unexpected error: "Expected number, got number".

**Comment by lupus590** [comment]
Issue is not present in [current source](https://github.com/dan200/ComputerCraft/blob/3e265c27ff080fd81deb0626d5f99fec9baa0a97/src/main/resources/assets/computercraft/lua/rom/apis/rednet.lua#L116), update your mod version (you may need to download from the [unofficial build server](http://cc.crzd.me/) as CurseForge is not always up to date)

**Comment by RedGalaxySoftware** [comment]
Already fixed it using emacs
