### ISSUE TITLE
[1.76pr4] Crash on breaking monitor

### ISSUE THREAD

**Issue by Wojbie** [dan200/ComputerCraft#52]
Place a monitor.
Place 2nd one to right of first so they connect.
Break left(first) one.
Crash.

http://pastebin.com/H5jV4Jxw

**Comment by dan200** [comment]
Which version of CC?

**Comment by Wojbie** [comment]
pr4
Sorry forgot to add that.

**Comment by dan200** [comment]
Might have introduced that as part of another fix then, investigating.

**Comment by dan200** [comment]
Found it. Fixed for pr5
