### ISSUE TITLE
setPaletteColor does not have a "Invalid color" error

### ISSUE THREAD

**Issue by IliasHDZ1** [dan200/ComputerCraft#524]
If you type for example:
`term.setPaletteColor(56, 16, 0, 0)`

56 is an invalid color.

and as an error. it returns: "window.lua:301: index expected, got nil"

**Comment by IliasHDZ1** [comment]
The version is:  ComputerCraft 1.80pr0

**Comment by Lignum** [comment]
Yes, this is a likely a problem with the `window` API. On normal computers, which do not have multishell, it should print "Colour out of range" like all the other term functions

**Comment by lupus590** [comment]
Looks like this is already fixed: https://github.com/dan200/ComputerCraft/blob/3b3dd8071bf9f1dcd60b6771682b9b1fa7ad1c15/src/main/resources/assets/computercraft/lua/rom/apis/window.lua#L291

**Comment by SquidDev** [comment]
What version of the mod are you running? The fix for that was merged before 1.80pr1 was released. I'd recommend updating to that (or even better, [a development build](https://cc.crzd.me/)).

**Comment by IliasHDZ1** [comment]
Oh. It doesn't matter anyway.
I was using an older version...
