### ISSUE TITLE
Spectator mode rightclicks

### ISSUE THREAD

**Issue by Lion4ever** [dan200/ComputerCraft#53]
The printer and the turtle only show 9 inventory spaces.
The diskdrive does not show any space.

The screen of the computers and turtles can not be seen. (I am not sure is this is a bug or good because there is no spying then).

Since the screen is not shown, nothing can be typed into the computer. This is important because otherwise it would break that gamemode.

**Comment by Lion4ever** [comment]
![dd](https://cloud.githubusercontent.com/assets/8234006/11788110/9508dc44-a28f-11e5-9155-408ff3b74df2.PNG)
![turtle](https://cloud.githubusercontent.com/assets/8234006/11788112/96411fd6-a28f-11e5-82bf-531f485e5922.PNG)

**Comment by dan200** [comment]
So, er, what's spectator mode?

**Comment by Wojbie** [comment]
New game-mode added in 1.8
http://minecraft.gamepedia.com/Spectator

**Comment by Lion4ever** [comment]
A gamemode added in 1.8.
/gamemode 3 or /gamemode spectator
Usually used for players that should not interact with the world. (because they are dead or not trusted)

**Comment by Wojbie** [comment]
http://minecraft.gamepedia.com/Spectator

**Comment by dan200** [comment]
Just had a look at the code for this. It looks like it's hardcoded to use the "GuiChest" inventory for everything. Forge would need to add a hook.

**Comment by Lion4ever** [comment]
is it possible to adjust the number of rows for the guiChest?

**Comment by AEnterprise** [comment]
it would be cool if spectators could have limited access to computers, maybe only watching not typing or only allow typing/clicking on the screen if the program calls a special command to allow it?

**Comment by dan200** [comment]
AEnterprise: As stated, forge does not supply a hook for this, and i'm uncomfortable adding new code for such a rarely-known feature.

Lion4Ever: It seems that guiChest determines rows by doing: (numberOfSlots / 9), ie: rounding down. Really it needs to round UP. I could maybe create a forge pull request changing this.

**Comment by dan200** [comment]
Closing this, as it's not solvable with forge atm.
