### ISSUE TITLE
[1.76pr4] Wierd looks of turtle and pocket computer labels.

### ISSUE THREAD

**Issue by Wojbie** [dan200/ComputerCraft#54]
![Image here](http://i.imgur.com/dZCem7A.png)
This is effect of
```
os.setComputerLabel(string.char(1,149,153,200))
```
On a turtle. When picked up it stays on label. Same thing with pocket computer names.
Probably not a bug but a unpredicted effect.

**Comment by dan200** [comment]
Yeah, the custom glyphs that ComputerCraft renders in place of the Control Characters are non-standard, so they'll inevitably look different when rendered in a different font (you'll see a similar thing if you write those chars to a file and open them in an text editor). I could strip them out when setting labels, but it might be better to leave them in to demonstrate a point :p
