### ISSUE TITLE
How do I build this.

### ISSUE THREAD

**Issue by midgethoen** [dan200/ComputerCraft#545]
Im trying to build this mod for playing since the latest release is ~500 commits behind. 
Im not a java guy though, so this is new ground for me and im running into all kinds of issues.

first of: setup.sh fails because gradlew doesnt work.
I've been able to work around this by installing  gradle myself and changing setup.sh

then  deploy shows a lot of errors and there doesn't seem to be a proper build in ./build.

also build_luaj.sh fails for me. al though I might not even need to run this.

**Comment by SquidDev** [comment]
There's two ways:

 • Don't! https://cc.crzd.me/ has pre-built versions of most branches, so if you don't want to make any modifications you can just use that.
 • Run `./gradlew setupDecompWorkspace` to setup Forge, then run `./deploy.sh` to build - the resulting file should be at `deploy/ComputerCraft-xxx.jar`

**Comment by midgethoen** [comment]
thnx for you quick response, ik was hit enter on accident and created the issue while I still wanted to type my message.

**Comment by midgethoen** [comment]
thnx for the tip! I will go with option one :)
