### ISSUE TITLE
computercraft.info registration broken

### ISSUE THREAD

**Issue by ZyorTaelon** [dan200/ComputerCraft#546]
The reCAPTCHA V1 that is used in the registration form of http://www.computercraft.info is discontinued.

Please change the registration form so we can register again.

**Comment by Wilma456** [comment]
This is the Repository for the Mod and not for the Website. And its also been reported here: http://www.computercraft.info/forums2/index.php?/topic/29549-recaptcha-v1-is-shutdown/

**Comment by ZyorTaelon** [comment]
Hi Wilma.

I know this issue tracker isn't meant for the website. But I couldn't register on the site to post about the problem with the registration...
(And I missed that it was already posted)

This seems like the most efficient way to reach the relevant people.

Thanks again for your speedy reply!

**Comment by lupus590** [comment]
The only relevant person is @dan200 none of the forum mods have the permissions needed to fix the forums.
