### ISSUE TITLE
Acces turtles from other mods

### ISSUE THREAD

**Issue by DevSven** [dan200/ComputerCraft#548]
Hi,
I am currently trying to develop an own mod for minecraft in which I want to control turtles via chat but I do not know how to connect a placed turtleblock in minecraft with a java object which I want to use to let the turtle do all its commands.

**Comment by theoriginalbit** [comment]
I did a similar thing in MoarPeripherals for the keyboard block. You can see some of the code to find a Turtle in the world [here](https://github.com/theoriginalbit/MoarPeripherals/blob/master/src/main/java/com/moarperipherals/util/TurtleUtil.java).
