### ISSUE TITLE
Computer won't boot on login

### ISSUE THREAD

**Issue by Dreossk** [dan200/ComputerCraft#549]
On a server, the computers don't boot when I login. I have to go to each one of them and interact (right-click) to boot em even if they were on before I logged off. I see many posts on the subjects over the years but never a solution. I also see a fix was posted here in September but it doesn't seem to work?
Version 1.80pr1

Edit: Wait, so I see there is a CC:Tweaked... Should I use that one? Was the bugged fixed there? Why maintain two mods?

**Comment by SquidDev** [comment]
I suspect this is similar to #95.

>  I also see a fix was posted here in September but it doesn't seem to work? [...] Wait, so I see there is a CC:Tweaked. Was the bugged fixed there? Why maintain two mods?

The fix (#457) hasn't yet been merged into CC, so if you're using the version on Curse or from cc.crzd.me then you won't have it. CC:Tweaked basically aims to be an experimental version of CC, and so gives as an opportunity to try out PRs like that one, and see if they actually do what they're meant to.

In this case, it definitely seems to be effective and I haven't had issues with computers shutting down (outside of server crashes). That being said, I'm not going to claim it's entirely effective so if you do find cases where they don't turn on, do get in touch!

**Comment by Dreossk** [comment]
I confirm the other mod seems to fix it.
