### ISSUE TITLE
[1.76pr4] Large fps drop when looking at multiblock monitors.

### ISSUE THREAD

**Issue by Wojbie** [dan200/ComputerCraft#55]
Fps seems to drop from 60 to 13-10-5 when working on max size monitor. 

![Example1](http://i.imgur.com/Rxia1Nk.png)
![Example2](http://i.imgur.com/8raHhSc.png)

**Comment by xAnavrins** [comment]
Same happens for me, when I tried to remove the monitor, this crash happened.
http://pastebin.com/2yhGyGLz

**Comment by Wojbie** [comment]
That crash is unrelated issue and has been resolved here:
https://github.com/dan200/ComputerCraft/issues/52

**Comment by dan200** [comment]
Reverted the change in pr4 that caused this (and came up with an alternate fix). pr5 should be back to pr3 performance.

**Comment by dan200** [comment]
Made some more improvements for pr5. Should now be at 1.75 speeds and above.
