### ISSUE TITLE
add getPosition() that does not rely on 4 computers acting as satellite. Reasons below.

### ISSUE THREAD

**Issue by DevL0rd** [dan200/ComputerCraft#551]
It would be nice to be able to get the current position of the computer/turtle/tablet computer.
I made a self learning bot with turtles in an old version of MC that used peripherals ++ to get exact position.

I also built a system where my tablet PC communicated with nodes at my base to auto open doors when i got near them or when i crouched, or to automatically select the nearest computer to send commands to.

The GPS setup for computer craft is far too inaccurate.
And it's extremely inefficient to keep making a bunch of 4 computer satellites that have limited range.
I don't think it should be a peripheral, unless you would like to add a peripheral that groups up to 4 peripherals so i can use the modem and the gps module at the same time.

Just having your position and wireless communication unlocks so much that you could code!

**Comment by theoriginalbit** [comment]
> The GPS setup for computer craft is far too inaccurate.

Sounds to me like you need to use more than 4 'satellites'. Just like in the real-world, the more GPS satellites you have access to result in a more accurate calculation.

Make sure that you avoid having satellites on the same `x` or `y` plane to ensure high `x`/`y` accuracy, and you definitely need to have a couple on different `z` planes to get an accurate result for your `z`; basically what I'm saying is spread out the satellites.

**Comment by lupus590** [comment]
There's always [LAMA](https://github.com/dirthsj/LAMA), you have to tell the turtle where it is once and then it tracks its movement to figure out its position when it needs it later.

Or you could use one of the many GPS deployment scripts which should place your GPS satellites in [optimal positions.](https://i.imgur.com/2P3XL.jpg)

**Comment by DevL0rd** [comment]
@apemanzilla Wow, I didn't know ender modems had higher accuracy over long distance.

@theoriginalbit i'll take your suggestion and try spreading satellites of different altitude and spread.

Also, @lupus590, My bot already works by keeping track of its relative position. however there are some instances where it can loose track of where it is at that i have ran into rarely. Regardless this solution of course does not apply to tablet computers.

**Comment by DevL0rd** [comment]
Thanks for the suggestions!

**Comment by lupus590** [comment]
@DevL0rd I've never had issues where a turtle running LAMA has gotten lost. LAMA uses fuel tracking to confirm that the movement succeeded, this allows LAMA to keep accuracy over chunk/server reloads. What are you using for turtle position tracking?

And yes, LAMA doesn't work with pocket computers, but the player could just check F3.
