### ISSUE TITLE
gap between turlte and monitor corners

### ISSUE THREAD

**Issue by Lion4ever** [dan200/ComputerCraft#57]
if you look closely there is a one pixel wide gap between the corners of the turtles and between the frame of a monitor and the screen. Moving closer ingame does not do anything since the line remains one pixel wide.
![t grap](https://cloud.githubusercontent.com/assets/8234006/11793060/d1e7b274-a2a9-11e5-8d2e-9bae4c5e74cc.PNG)
![m](https://cloud.githubusercontent.com/assets/8234006/11793068/d6cc4192-a2a9-11e5-9dcc-aceaed331fe5.PNG)

**Comment by xAnavrins** [comment]
I think this is something with your GPU drivers, it used to do that on my friend's Minecraft, and it doesn't only happens on turtles or monitors.

**Comment by Lion4ever** [comment]
i tested this with many vanilla blocks and it did not happen there...

**Comment by dan200** [comment]
This is just a floating point accuracy issue, can't do much about it.
