### ISSUE TITLE
rednet causing lan players to get kicked?

### ISSUE THREAD

**Issue by monkeybee11** [dan200/ComputerCraft#572]
when ever me try to sue the pocket computer to send a message to a computer my dad gets kicked from my open to lan world im not able to find forge logs for some unknown rasin but heres the only log file im able to find 
[latest.log](https://github.com/dan200/ComputerCraft/files/2319509/latest.log)

**Comment by monkeybee11** [comment]
[fml-client-latest.log](https://github.com/dan200/ComputerCraft/files/2319522/fml-client-latest.log)
 ive found the forge log

**Comment by apemanzilla** [comment]
Is everyone involved using the same versions of the mods?

**Comment by monkeybee11** [comment]
yes but ignore this ive found out the problem is with funky locomotion not computercraft
