### ISSUE TITLE
REQUEST: Parameter to turtle.dig to choose what side/tool to use

### ISSUE THREAD

**Issue by vpontin** [dan200/ComputerCraft#579]
While dual wielding for turtles came back in 1.6 we still can properly use two equipped tools at once, simply because we cant declare what side we want to perform those dig actions.

Currently from personal experience the preferable tool for the block is chosen, but it can lead to some issues when the block is dirt-like and uses a shovel or hoe to be broken. Since the "attack" and "use" functions are triggered (use by preference) by dig functions in these cases the grass block (for example) will not be broken, just converted to grass path, and the dev need to add extra care in the code to workaround this issues.

Like i said in #564 adding those features (the parameter and possibly turtle.use separately) would ease the development of lua scripts for turtles (with dual tools) and not shoo away beginners.

**Comment by KnightMiner** [comment]
Can't we already do that? I remember it being possible in 1.7 by calling `turtle.dog("left")` or `turtle.dig("right")`

**Comment by vpontin** [comment]
really? I didnt find anything about this on any wikis (the original one or @SquidDev's CC:Tweaked one)

**Comment by KnightMiner** [comment]
Yep, see https://github.com/dan200/ComputerCraft/blob/master/src/main/java/dan200/computercraft/shared/turtle/apis/TurtleAPI.java#L206-L207

**Comment by SquidDev** [comment]
> 
> 
> really? I didn't find anything about this on any wikis

I've updated both wikis to mention the `toolSide` parameter. Can this issue be closed - I don't think there's anything else which needs doing?

**Comment by vpontin** [comment]
Thanks
