### ISSUE TITLE
Redstone setBundledOutput Issue

### ISSUE THREAD

**Issue by NillerMedDild** [dan200/ComputerCraft#581]
Hello!

the function `redstone.setBundledOutput(string side, number color)` does not function with EnderIO cables in 1.12.2 - It is incapable of sending redstone signals.

- Minecraft 1.12.2
- Forge 1.12.2-14.23.5.2768
- ComputerCraft 1.79
- EnderIO-1.12.2-5.0.37

**Comment by SquidDev** [comment]
This is on EnderIO's end: they removed their integration a couple of months ago as CC was getting increasingly hard to build against.

**Comment by NillerMedDild** [comment]
Alright, thank you :)
