### ISSUE TITLE
Q: Where to download

### ISSUE THREAD

**Issue by Inve1951** [dan200/ComputerCraft#585]
I'm looking for the latest CC for mc v1.12.2.

I see @SquidDev got a bunch of new feature branches in their fork.
Is that where development mainly takes place atm?

Where can I find the latest master/head release/download?
I'm a total noob when it comes to git branches and got no clue how to merge @SquidDev's branches into a single release.

Btw, the download/mcforum link from the [wiki](http://www.computercraft.info/wiki/Main_Page) needs a twitch login?!

**Comment by SquidDev** [comment]
Honestly, you're probably better off using [CC:Tweaked](https://minecraft.curseforge.com/projects/cc-tweaked) if you're interested on some of the PRs I've put together.

**Comment by Inve1951** [comment]
Sweat, thanks. :+1:
