### ISSUE TITLE
Suggestion: graphical functions for monitors and terminals

### ISSUE THREAD

**Issue by someone0010** [dan200/ComputerCraft#591]
I'd like to suggest some graphical functions for drawing on the screen, like .fillrect, .drawline, etc.. instead of obsolete .write(" ") which is kinda boring. It also would make the limits of making GUIs better.

**Comment by JakobDev** [comment]
Take a look at the [paintutils API](https://wiki.computercraft.cc/Paintutils_API)

**Comment by someone0010** [comment]
Thanks, I'll take a look.
