### ISSUE TITLE
Using a lua .jar file in your mods folder breaks computercraft.

### ISSUE THREAD

**Issue by moo1210** [dan200/ComputerCraft#598]
Using a luaj jar file will completey break computercraft, making computers unable to boot.  I would like to be able to use that luaj without breaking computercraft if possible. I am using computercraft 1.7.10  1.7.5 (latest for mc 1.7.10)

**Comment by moo1210** [comment]
Or is it possible computercraft already has a luaj and this luaj is overwriting it and it needs a different version?

**Comment by KnightMiner** [comment]
Why are you putting luaj in your mods folder? Does another mod depend on it? Because if so, that's a bad way to add the library.

You should also post game logs for this type of issue, though as a warning I would not expect a fix of this turns out to be a ComputerCraft issue as 1.7.10 is so old.

**Comment by SquidDev** [comment]
From memory, this is an optional dependency of Custom NPCs. I think you can get away without it, just won't have Lua support. 

However, as KnightMiner says 1.7.10 is terribly old at this point, and so is no longer maintained.

**Comment by moo1210** [comment]
I wanted lua support, but whatever I'll just use python with custom npcs.
