### ISSUE TITLE
[1.76pr5] Wierd monitor background is a font file?

### ISSUE THREAD

**Issue by Wojbie** [dan200/ComputerCraft#60]
I don't even know how to call this one. Suddenly all my monitors/computers are looking like this:
![1](http://i.imgur.com/Vxc3JL5.png)
![2](http://i.imgur.com/HIek53i.png)
![3](http://i.imgur.com/yapecC0.png)
![4](http://i.imgur.com/UYK350C.png)

Change happened suddenly. 
Persisted between worlds
I attempted:
minecraft restart 
computer restart
clean download of mod 
ComputerCraft downgrade and re-upgrade (downgrade fixed it but upgrade re-broke it)
And this persisted.

I found that when making a clear minecraft install (new profile) on same computer fixes it but i am not sure if that will not came back. I still have bugged profile if you need it.

**Comment by dan200** [comment]
Er, wow... I dare to ask, but: any repro steps?

**Comment by Wojbie** [comment]
I have no idea. I left minecraft running in background and when i looked back it it it was like that.

**Comment by dan200** [comment]
Also, which version of CC? I presume pr5?

**Comment by Wojbie** [comment]
I forgot to add that again..... Yea pr5

**Comment by Luca0208** [comment]
Maybe the bug only occurs on some graphic cards, I had some problems with other mods, which seemed to be because of my graphics card. What graphics card do you have Wojbie?

**Comment by Wojbie** [comment]
Point is. It happend without a reason i can see and is isolated to one luncher profile. I am trying to recreate situation on 2nd profile. No success(or is it failure?) so far.

**Comment by Wojbie** [comment]
Idea. I can pack up corrupted profile and send it to You dan200. Would that help you trace the source?

**Comment by BombBloke** [comment]
My bet is you somehow managed to replace termBackground.png with termFont.png while developing your BigFont API - the two files are right next to each other within assets\computercraft\textures\gui. The actual symptoms wouldn't appear until the game had cause to reload them (eg when you later restarted it).

In your new profile you likely used a clean copy of the mod.

**Comment by Wojbie** [comment]
Well that's the thing bomb bloke. I replaced mod file with new one clean from website and problem persisted. But until someone else gets same problem I guess my computer is just weird.

**Comment by dan200** [comment]
Let's try one thing:could you create a new world on the "broken" instance,
without loading the other one first, and see if it occurs. If it doesn't,
then loading the older world causes it, then we'll know it's triggered by
that save. If so: I'd like a copy of that save to see if I can reproduce
here.

**Comment by Wojbie** [comment]
As usual simplest explanation totally eluded me. 
Here is save game that is triggering the bug.
https://www.dropbox.com/s/1j80nfxjlzh10r3/New%20World--.rar?dl=0

For bug to happen it has to be loaded as first saved game. IF any other save is loaded before and then this one is loaded the bug don't happen.

**Comment by dan200** [comment]
Thanks for this. I was able to reproduce the problem using your save.

It seemed that for some reason, if an active monitor was the very first thing to be rendered that uses the termBackground or termFont textures, they'd somehow end up getting bound to the same OpenGL texture ID (and therefore, all subsequent binding of one would bind the other). I've no idea how this happened, but i've reordered some of my rendering code to more closely match the 1.7.10 code, and I can no longer reproduce this.

Let me know if this still recurrs for you once pr6 is released.
