### ISSUE TITLE
Printed Pages don't overlay colors

### ISSUE THREAD

**Issue by MaximPixel** [dan200/ComputerCraft#602]
If you print something else on already printed paper, only the last layer will be displayed.

**Comment by SquidDev** [comment]
This was fixed in back in 2017 by bfb4f88304a52d4beabc1252f0b7450dbca318c8. However, there hasn't been a new release since then.

I recommend one of the more regularly updated forks, such as [CC: Tweaked](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked).
