### ISSUE TITLE
Suggestion: Monitors larger than 8x6

### ISSUE THREAD

**Issue by Tairex777** [dan200/ComputerCraft#603]
There should be a way to increase the maximum monitor size in the config. It just seems weird not to have it. Also I need it in 1.7.10. Thanks.

**Comment by SquidDev** [comment]
![](https://squiddev.cc/r/let-it-1.7.10.png)

**Comment by Tairex777** [comment]
?!?!?!??????

**Comment by Tairex777** [comment]
Searching it just comes up with Elsa.

**Comment by vico93** [comment]
He's saying for you to let 1.7 go...

**Comment by lupus590** [comment]
Try this: http://www.computercraft.info/forums2/index.php?/topic/18229-multimon-multiple-monitors-in-computercraft/

**Comment by Tairex777** [comment]
1.7.10 just had the most mods and I'm playing on a locally hosted server with no port fowarding.
I have 32 mods enabled and don't want to lose them.

**Comment by Tairex777** [comment]
That is perfect!

**Comment by Tairex777** [comment]
But this should be considered for the haters of the split lines. (Separation between display clusters)
