### ISSUE TITLE
Pastebin not working in 1.75

### ISSUE THREAD

**Issue by turbocat2001** [dan200/ComputerCraft#605]
The pastebin links have changed slightly. Here's my fix:
[ComputerCraft1.75-fix.zip](https://github.com/dan200/ComputerCraft/files/5596579/ComputerCraft1.75-fix.zip)

**Comment by Lupus590** [comment]
A few things:

First: this repo is practically dead, and [CC: Tweaked](https://github.com/SquidDev-CC/CC-Tweaked) is the defacto continuation.

Second: I don't think that a version that old will get support, I know that SquidDev (maintainer of CC:T) is only supporting MC 1.16 and 1.15

Third: there is already a [fix](https://github.com/Wendelstein7/FAQBot-CC/blob/master/faqs/pastebin-pre1.8.md) for this

**Comment by turbocat2001** [comment]
Do not tell me where this fix is ​​located

ср, 25 нояб. 2020 г., 16:25 Lupus590 <notifications@github.com>:
