### ISSUE TITLE
Get error : "Response is too large" with "http.get" command

### ISSUE THREAD

**Issue by Axelouuu-dev** [dan200/ComputerCraft#620]
Hi !

I try to download a file from my website but it give me the error "Response is too large".

In computercraft-server.toml config file, I've tried to up space_limit to 1Go, max_request to 0 and brandwidth to 2147483647.

The file I try to download weighs 17Mo.

![image](https://github.com/dan200/ComputerCraft/assets/19538750/d7e7b902-f473-4f62-89ab-e0b74d200f58)

Is there possible to increase the limit ?

**Comment by vico93** [comment]
If you are using CC:Tweaked (the fork of original Computercraft post 1.8 if i'm not mistaken), redirect the issue to https://github.com/cc-tweaked/CC-Tweaked

**Comment by Axelouuu-dev** [comment]
Ah yes, sorry !
