### ISSUE TITLE
[suggestion]add multi-language support for official wiki

### ISSUE THREAD

**Issue by HfSrJun** [dan200/ComputerCraft#623]
I don't know if the official wiki is still maintained by someone. But I think it would be useful if you add multi-language pages for it, just like OC does (although its translation is far from finish).
Many players from non-English countries are playing CC, as its useful for automation. But the English wiki is still a difficulty for most players. Maybe a local language wiki will decrease the difficulty for players.
I can participate in translation for zh_cn language, like I had already done for some mods, like TIS-3D and Advanced Peripherals.

**Comment by Lupus590** [comment]
CC isn't used anymore, were you looking for [CC:Tweaked](https://github.com/cc-tweaked/CC-Tweaked)?

Also, two of the wikis are unmaintained and the current maintained one [tweaked.cc ](https://tweaked.cc/) is generated from source code for the most part and thus not the easiest to translate.

**Comment by HfSrJun** [comment]
> CC isn't used anymore, were you looking for [CC:Tweaked](https://github.com/cc-tweaked/CC-Tweaked)?
> 
> Also, two of the wikis are unmaintained and the current maintained one [tweaked.cc ](https://tweaked.cc/) is generated from source code for the most part and thus not the easiest to translate.

of course, I mean tweaked. I always ignore the difference between the tweaked one and the old one, my apology.
the wiki I often read when programming is https://www.computercraft.info/, it seems that it is abandoned.
tweaked.cc has many fancy contents such as running the code, that is amazing.

so it seems that the multi-language wiki have to be built from scratch, if I have time maybe I will build it on some free wiki platform.

**Comment by Lupus590** [comment]
> of course, I mean tweaked.

This is the old repo, I linked the new one. You probably want to copy this issue to that repo.

> https://www.computercraft.info/, it seems that it is abandoned.

Because it is, [tweaked.cc](https://tweaked.cc/) is the only supported wiki/documentation site at current.

> so it seems that the multi-language wiki have to be built from scratch

Maybe not, @SquidDev wrote the software that generates [tweaked.cc](https://tweaked.cc/) and might be able to add translation support to it.
