### ISSUE TITLE
Pastebin GET Command Broken

### ISSUE THREAD

**Issue by VisualStudio-zz** [dan200/ComputerCraft#64]
Pastebin updated their website recently and raw pastes aren't retrieved using HTTP GET args in the url like raw?i=(paste id), it's been changed to a virtual directory like this /raw/(paste id)

The problem is here:
/rom/programs/http/pastebin @ line 24

Fix:
```
"http://pastebin.com/raw.php?i="..textutils.urlEncode( paste )
```
change to:
```
"http://pastebin.com/raw/"..textutils.urlEncode( paste )
```

**Comment by dan200** [comment]
Fixed for pr6. Thanks

**Comment by VisualStudio-zz** [comment]
No prob.
