### ISSUE TITLE
Crashes client when opening 

### ISSUE THREAD

**Issue by EternallyBored** [dan200/ComputerCraft#65]
I added the latest version of the client to my mods and sadly it keeps crashing when forge loads them   :(  I tried this 3 times to make sure it wasn't a 1 time issue.  Here are the reports

Thats with extreme launcher 2.3.1.16 and ComputerCraft 1.76 Beta (Updated December 16th)

[crash-2015-12-16_12.30.41-client.txt](https://github.com/dan200/ComputerCraft/files/64392/crash-2015-12-16_12.30.41-client.txt)

**Comment by dan200** [comment]
You have too many mods installed to effectively debug this. Please try to
reproduce with just forge and CC.

**Comment by EternallyBored** [comment]
Hope this helps

[crash-2015-12-16_15.38.22-client.txt](https://github.com/dan200/ComputerCraft/files/64603/crash-2015-12-16_15.38.22-client.txt)

**Comment by dan200** [comment]
Try a newer version of Forge. Yours is from June.

**Comment by EternallyBored** [comment]
So I used your site to go to Forge's, went to there latest download, ran it and selected install, left that for a few and came back, everything appeared to have finished and opened forge again and got this report

[crash-2015-12-16_17.54.12-client.txt](https://github.com/dan200/ComputerCraft/files/64733/crash-2015-12-16_17.54.12-client.txt)
[crash-2015-12-16_17.55.59-client.txt](https://github.com/dan200/ComputerCraft/files/64734/crash-2015-12-16_17.55.59-client.txt)

My computer has always been a bit wonky so I thought maybe it needed a restart to make sure everything was working ok so I selected shutdown, let it sit for a minute and booted it back up, after everything loaded I tried running the client again and got this message

[crash-2015-12-16_18.05.51-client.txt](https://github.com/dan200/ComputerCraft/files/64736/crash-2015-12-16_18.05.51-client.txt)

I've only had 3 hours of broken sleep the last 48 so not sure if I missed something or did something wrong

**Comment by dan200** [comment]
All those crash logs show the same, old, forge version. This thread has
moved from bug report to tech support so I'm closing this now.

**Comment by EternallyBored** [comment]
Thanks, I'll try to figure out how to update than

**Comment by apemanzilla** [comment]
@EternallyBored, try using the latest recommended version for *1.8* (not 1.8.8) from [here](http://files.minecraftforge.net/)

**Comment by BombBloke** [comment]
Also remember that if you're using the regular Minecraft launcher to start the game, after installing a given Forge build you'll still need to select a Profile within the launcher that makes use of it.
