### ISSUE TITLE
[1.76pr6] Compatibility for MC1.8.8

### ISSUE THREAD

**Issue by Nokiyen** [dan200/ComputerCraft#69]
This is not a bug, but just a request.
Sorry, If you already check this kind of thing.

Current pre versions are compatible only for MC 1.8.
And, it seems to be possible to work with forge and mc 1.8.8 just by @ mod annotations like;

```Java
@Mod(~~~, acceptedMinecraftVersions="[1.8,1.8.8]")
```

I've checked some mods are compatible for both 1.8 and 1.8.8 by this way.
But I don't know all of mods can...

**Comment by dan200** [comment]
Forge for 1.8 and Forge for 1.8.8 have incompatible APIs.
THere will be a 1.8.8 version, but not until the 1.8 version has shipped.
