### ISSUE TITLE
Page Up/Down Not Working

### ISSUE THREAD

**Issue by DeGariless** [dan200/ComputerCraft#7]
I believe the page up and down buttons used to work in ComputerCraft. They currently do not seem to be working. (CCv1.6.4) Tested with: while true do print(os.pullEvent()) end

**Comment by dan200** [comment]
Page up and page down work just fine. it's possible another mod is interfering

**Comment by Wojbie** [comment]
@DeGariless Close the NEI interface and try again. Its most common reason for those key presses not working. By default its o key with inventory open.
