### ISSUE TITLE
Crash when turtle places disk drive

### ISSUE THREAD

**Issue by apemanzilla** [dan200/ComputerCraft#70]
From [here](http://www.computercraft.info/forums2/index.php?/topic/25404-176pr4ssp-turtle-placing-disk-drive/):
>I have not tested this SMP, may have similar problems.
>
>VERSION:
>1.76pr4 for Minecraft 1.8.
>
>DESCRIPTION:
>Minecraft is crashing every time a turtle places a disk drive. Upon reloading the world a duplicate disk drive is found inside of turtle, with another disk drive placed in front of the turtle. Placed disk drive seems to interact normally with computers. 
>
>EXPECTED RESULT:
>Minecraft not to crash/duplicate disk drive.
>
>REPRODUCTION STEPS:
>Give a turtle a disk drive and call turtle.place(), turtle.placeUp() or turtle.placeDown() in Lua prompt or any written programs.
>
>Minecraft pastebin crash report if needed: http://pastebin.com/Z0DE6E8g

**Comment by Wojbie** [comment]
Confirmed in pr6
http://pastebin.com/QrS7x0QG

**Comment by dan200** [comment]
Can somebody try this with all the other CC peripherals/computers and tell me if it crashes for those too?

**Comment by Wojbie** [comment]
### Safe: 
Printer
Monitor and Advanced Monitor.
Modems - Wired, Wireless and Long Rage
Cable

### Broken:
Disk Drive - Crash: http://pastebin.com/QrS7x0QG

Turtle,TurtleExtended,TurtleAdvanced - Crash http://pastebin.com/Pr6ayxA7

Computer - Crash http://pastebin.com/xXaQncMh and map corrupts http://pastebin.com/6ySQxmap
Advanced - Same as above
Command - Same as above

In cases when it crashes but map is not corrupted the item gets placed and is not removed from inventory.

**Comment by dan200** [comment]
Fixed in pr8
