### ISSUE TITLE
1.76pr6 Normal turtles are not explosion-proff / blast resistant.

### ISSUE THREAD

**Issue by Wojbie** [dan200/ComputerCraft#71]
I just tested it and found out that only advanced turtles are blast resistant.
Basic ones get blown up.

**Comment by dan200** [comment]
In previous versions, turtles were resistant to explosions from creepers
and nothing else. Now: all types are resistant to creepers, and advanced
areresistant to all. Does this match your observations?

**Comment by Wojbie** [comment]
OK now i feel like in twilight zone or something. I could swear i had creeper blow up normal turtle but now i can't reproduce. If i am able to reproduce it by accident later i will comment here for reopening.

**Comment by Wojbie** [comment]
Just an update on issue:
I was able to blow up the basic turtle using creeper or Danny's 1.8 pr6 server:
http://www.computercraft.info/forums2/index.php?/topic/25388-acora-server-mc-18cc-176pre6/

As soon as I can contact him. I will try to get modlist from him I will try to get some kind of reproduction method going. Could be connected to one of other mods on server.

**Comment by BombBloke** [comment]
According to this:

http://minecraft.gamepedia.com/Creeper#History

... MC1.8 makes creepers more "deadly". I assume that translates to increased damage to blocks, too. No idea.

They apparently have an explosive power of 3 (or 6 if lightning-charged). TNT has a power of 4.

Gamepedia doesn't seem to have power levels listed for the older MC1.7.10, merely stating that they depend on the game difficulty (whereas they should always be the same under MC1.8):

http://minecraft.gamepedia.com/index.php?title=Creeper&oldid=740580

**Comment by Wojbie** [comment]
Good note. Redoing test with difficulty settings.

**Comment by Wojbie** [comment]
Nope. Even on hard turtle survived the explosion. Waiting for Danny modlist.

**Comment by BombBloke** [comment]
Rather, I was saying difficulty should matter under 1.7.10, but not under 1.8.

Testing it myself using some monster eggs and flint&steel, I can't get any creepers to take out turtles under pr8.
