### ISSUE TITLE
Reading from file, Teletext charaters

### ISSUE THREAD

**Issue by Yoshi-EE** [dan200/ComputerCraft#72]
File to read from: http://pastebin.com/X1uwmXeb

Reading the charater "£" from a file results in "Â£". So in this case the line in the file and printing it, using print():
<span class="teletextGraphics">&nbsp;!&quot;£$%&amp;'()...
results in:
<span class="teletextGraphics">&nbsp;!&quot;Â£$%&amp;'()...

Tested on 1.7.6pr6

**Comment by dan200** [comment]
Try again in pr8. I recently fixed some stuff in this area.

**Comment by Yoshi-EE** [comment]
seems to be fixed now, thanks
