### ISSUE TITLE
Can't Craft Bonemeal

### ISSUE THREAD

**Issue by cleverlike** [dan200/ComputerCraft#74]
When a Crafty Turtle has only bone in it's inventory (tested all slots) it will not produce Bonemeal with the turtle.craft() command.  The command returns False.

**Comment by cleverlike** [comment]
Tested in CC1.7.4 on MC1.7.10 and it worked correctly.

**Comment by dan200** [comment]
Fixed for 1.76p9. This was affecting all Shapeless Recipes. Thanks
