### ISSUE TITLE
Turtle.place working weird

### ISSUE THREAD

**Issue by peon2** [dan200/ComputerCraft#76]
Turtle.place doesn't reliably place blocks facing the same direction. Seems to be based on movement of turtle before placing. I haven't found anything in change logs or forums so I can only assume its a bug. I've tested both 1.76pr8 and 1.75. 

[testing code]
turtle.select(1)

turtle.down()
turtle.place()

for i = 1, 2 do
  turtle.up()
  turtle.place()
end

[result]
![2015-12-22_16 54 58](https://cloud.githubusercontent.com/assets/16403450/11960954/49874ba4-a8cd-11e5-8599-05b1a3b10d29.png)

**Comment by peon2** [comment]
Is this intended? Blocks seem to face the opposite direction.

**Comment by dan200** [comment]
Placement rules (for forward placement) are as follows:
If there is a block directly in front of turtle, it places onto that.
Else, if there is a block below the space in front, it places down onto
that.
Else, if there is a block behind the space in front, it places across onto
that.

Does this match your observations?

**Comment by dan200** [comment]
Oh: if there's no blocks nearby, it places backwards onto itself.

**Comment by peon2** [comment]
So because there is nothing underneath the first set of blocks they place backwards, but since the second and third layers have blocks underneath them they place normally. Thanks for the clarification!

**Comment by dan200** [comment]
No worries, glad to be of help
