### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by ImUrX** [dan200/ComputerCraft#80]
http://pastebin.com/wYMf7BdE

**Comment by BombBloke** [comment]
( Minecraft 1.7.10 / Computercraft 1.75 )

Suspect this thread is relevant:

http://www.computercraft.info/forums2/index.php?/topic/23903-174-crash-with-colored-lights-core/

And indeed, in your load order we've got:

 coloredlightscore{1.3.7.39} [Colored Lights Core] (minecraft.jar) 

If disabling that doesn't help, you'll want to start disabling other mods until you've narrowed it down to which one(s) are involved. Disabling sets of 50% at a time should speed the process.

**Comment by dan200** [comment]
Closing, as this bug is not present in latest ComputerCraft
