### ISSUE TITLE
Add support for binary data over HTTP

### ISSUE THREAD

**Issue by oddstr13** [dan200/ComputerCraft#81]
The [HTTP API](http://www.computercraft.info/wiki/HTTP_%28API%29) does not currently support reading or posting binary data.

@Vexatos convinced me to put this here.

**Comment by dan200** [comment]
This is a feature request, not a bug

**Comment by oddstr13** [comment]
![enhancement label](https://dl.dropboxusercontent.com/u/4306267/ShareX/2016/01/2016-01-12_21-31-04.png)

Not sure of how to actually add the label, but you can sort by them there.

**Comment by dan200** [comment]
This issue tracker is for bug reporting only

**Comment by oddstr13** [comment]
You are way too quick on closing issues.

**Comment by apemanzilla** [comment]
@oddstr13 Dan just said - this is for **bug reporting**. If you want to post a suggestion, I advise you post [here](http://www.computercraft.info/forums2/index.php?/forum/20-suggestions/) instead. Additionally, this has been suggested before multiple times and the current solution is to just use base64 or another method of encoding the payload data.

**Comment by oddstr13** [comment]
@apemanzilla using an alternative encoding might be an acceptable solution in some cases, but only when you control the server side. It is not practical in most cases.

When it comes to the suggestion forums, this particular enhancement has been suggested several times over the years;
 * February 2013 - [slight modification to HTTP (affects returned file handle only)](http://www.computercraft.info/forums2/index.php?/topic/10383-slight-modification-to-http-affects-returned-file-handle-only/)
 * September 2014 - [Binary HTTP handles](http://www.computercraft.info/forums2/index.php?/topic/20478-binary-http-handles/)
 * April 2015 - [HTTP Enhancements](http://www.computercraft.info/forums2/index.php?/topic/22883-http-enhancements/)

Last one also suggest some other nice additions to the HTTP API.
Not sure if @dan200 has seen any of these threads, but he has not replied to them.
