### ISSUE TITLE
request: Binary files with Wget

### ISSUE THREAD

**Issue by columna1** [dan200/ComputerCraft#82]
I do a lot with binary things so I would like to have the ability to download binary fines. I have created workarounds that work well but I feel it would be a nice feature to have the wget program download those binary files without inserting those "?"s everywhere which turns the files to garbage. (maybe a binary mode for http?) 

also, I haven't tested this but wouldn't this also apply to utf-8 encodings? if you were downloading a utf-8 file you might get those question marks still.

**Comment by columna1** [comment]
oops. didn't look at closed issues like an idiot

**Comment by dan200** [comment]
To answer your question: CC 1.76 and above deliberately decodes all opened text files and http downloads using UTF-8, so as long as the file only contains the characters that CC supports in-memory (unicode characters less than 256, ie: the ISO/IEC_8859-1), utf-8 encoded, you'll get no data loss.
