### ISSUE TITLE
[1.78] Phantom Peripherals

### ISSUE THREAD

**Issue by BombBloke** [dan200/ComputerCraft#83]
Connect a peripheral to a computer via a pair of wired modems, and then break the peripheral. The computer will still act as if the peripheral is connected - eg, peripheral.wrap("printer_0") returns a table populated with usable functions even if the referenced printer no longer exists.

Peripherals placed directly next to computers before breaking do not trigger this. Breaking the modems (or "disconnecting" them) also doesn't seem to cause a problem.

Bug also existed under 1.76.

**Comment by dan200** [comment]
According to SquidDev, this is fixed

**Comment by SquidDev** [comment]
@dan200 Ahhh, sorry I may have confused things. #227 provides a commit (b39d765b3af178a0a9776a1345cd5bb59afca726) which fixes this, it just hasn't been merged yet.
