### ISSUE TITLE
[1.77pr0] settings API issues

### ISSUE THREAD

**Issue by BombBloke** [dan200/ComputerCraft#84]
copy() incorrectly checks the type of "v" instead of "value" (line 18). This won't directly generate an error, but'll prevent proper recursive copying of tables.

load() will fail silently if the targeted file can't be opened for read access (eg it's locked), or if it otherwise can't be parsed.

save() could stand to check that it successfully opened a file handle, as well.

**Comment by dan200** [comment]
Solved for 1.77pr1
Small note: In future, please try to get the name right when reporting problems with APIs/programs/methods!
