### ISSUE TITLE
ComputerCraftAPI.getBundledRedstoneOutput always returns -1

### ISSUE THREAD

**Issue by Vexatos** [dan200/ComputerCraft#86]
`ComputerCraftAPI.getBundledRedstoneOutput` always returns -1 because its `side` variable is an int while the method being invoked takes an EnumFacing instance, making it throw an `IllegalArgumentException: argument type mismatch`. I guess this is an oversight but it makes it impossible to add bundled redstone support in 1.8.9 without accessing core CC code directly.

**Comment by dan200** [comment]
Yep, this is a mistake. Will be fixed in next update. Thanks for spotting it.

**Comment by Vexatos** [comment]
I figured since it looks like there should be an `EnumFacing` in the API. It probably won't hurt too much to "break" the API at this stage since there aren't many CC addons for 1.8.9 out there yet and this feature wouldn't be working anyway.

**Comment by dan200** [comment]
Fixed for 1.79

**Comment by dan200** [comment]
(in the mean time, feel free to use reflection to call the method ComputerCraftAPI.getBundledRedstoneOutput calls with proper arguments)

**Comment by Vexatos** [comment]
I am temporarily just using the [core method](https://github.com/asiekierka/Computronics/blob/1.8/src/main/java/pl/asie/computronics/integration/charset/wires/CCBundledRedstoneIntegration.java#L106). Works just fine.
