### ISSUE TITLE
[1.78] Downwards-Facing Monitors Cosmetics

### ISSUE THREAD

**Issue by BombBloke** [dan200/ComputerCraft#87]
If an multi-block advanced monitor (at least 2x2) is constructed facing downwards, with its "topmost" edge pointing east, then its northwest (or "bottom rightmost") corner block will glitch out.

![2016-02-19_11 47 14](https://cloud.githubusercontent.com/assets/12162603/13163397/cc7c1c04-d700-11e5-8a69-22ec1c4221c3.png)
![2016-02-19_12 00 54](https://cloud.githubusercontent.com/assets/12162603/13163403/d84808ae-d700-11e5-82fa-e982615b914b.png)

**Comment by dan200** [comment]
Fixed for 1.79. I had to build some fun test structures to test every single monitor orientation!
![2016-02-26_17 59 28](https://cloud.githubusercontent.com/assets/1956716/13360811/d27513a6-dcb2-11e5-8acf-542486157aa5.png)

**Comment by BombBloke** [comment]
Heh, I did forget to test the upwards-facing displays more thoroughly. I hope you linked them up as disco lights afterwards!  ;)
