### ISSUE TITLE
Crash when connected to FunkyLocomotion Pusher

### ISSUE THREAD

**Issue by ryanhemmet** [dan200/ComputerCraft#9]
I did not think it would have many, (if any) methods. I just wanted to see if any methods what so ever were listed. So I got a peripheral proxy and connected it to the FunkyLocomotion Pusher and clicked the modem. The result of this is http://pastebin.com/mKBPz0zU.

**Comment by dan200** [comment]
Something you have installed is shipping a very old version of the ComputerCraft API
