### ISSUE TITLE
[1.79] table.pack does not set n.

### ISSUE THREAD

**Issue by SquidDev** [dan200/ComputerCraft#90]
`table.pack` should set the size of the table (as per the [Lua reference manual](http://www.lua.org/manual/5.3/manual.html#pdf-table.pack)), but does not 

```lua
table.pack = function( ... ) return { ... } end
```
Should be
```lua
table.pack = function( ... ) return {n=select('#',...), ... } end
```

**Comment by dan200** [comment]
Fixed for 1.78pr1
