### ISSUE TITLE
LuaJ String bugs

### ISSUE THREAD

**Issue by SquidDev** [dan200/ComputerCraft#91]
This aren't bugs with ComputerCraft but with LuaJ. I understand that this isn't within the scope of this bug tracker, just thought it might be useful.

 - `string.gmatch` will loop forever on non-consuming patterns (such as `\n*`)
 - `\011` is not counted as whitespace.
 - `string.format` does not pad/truncate on string of floating point format codes (`%s`, `%f`, `%g`, etc...)
 - Balanced matches (`%b`) throw an out of bounds exception on no match

I've got a set of [fixes and test cases](https://github.com/SquidDev/luaj.luajc/commit/8e682b9f98d2246b8dc3b85d68d71bd272a95874) if you want to fix/test this. This doesn't correctly handle the `%g` modifier.

---

I've also [added a fix](https://github.com/SquidDev/luaj.luajc/commit/b009741977ebf3b7d5f998b289e562c82a5467df) for `string.find` returning the wrong index on a previous match (which I guess is what the `string.find` and `string.match` overrides in `bios.lua` are for).

**Comment by dan200** [comment]
Fixed the string.find bug in my LuaJ fork and removed the bios.lua hacks. May merge in the other fixes later.

**Comment by dan200** [comment]
Fixed the infinite loop, whitespace not matching \v (this is actually caused by a typo in the original code, which i corrected), and the out of bounds exception. I will not be implementing the string.format fixes due to code complexity and relative unimportance.

**Comment by SquidDev** [comment]
Awesome! Thanks.
