### ISSUE TITLE
[1.79pr1] Crashes Dedicated 1.8.9 b1764 server on startup

### ISSUE THREAD

**Issue by kreezxil** [dan200/ComputerCraft#92]
Issue: computer craft 1.79pr1 crashes dedicated forge server 1.8.9 b1764 on startup

crash report:
https://gist.github.com/b523b5a0b0d2d2dff37e

fml server latest:
https://gist.github.com/bbcd743c1b873060a1ed

**Comment by SquidDev** [comment]
Remove CCTweaks: I haven't updated it so the pre-releases yet.

**Comment by dan200** [comment]
Caused by (somewhat dangerous!) third party mod. Closing
