### ISSUE TITLE
[1.79pr0] dofile broken

### ISSUE THREAD

**Issue by apemanzilla** [dan200/ComputerCraft#96]
![Screenshot](https://i.imgur.com/34jx1w8.png)
This seems to be happening due to [a typo in the `dofile` function](https://github.com/alekso56/ComputercraftLua/blob/master/bios.lua#L566-L574) - `fnFile` and `e` are never defined but not set.

**Comment by CrazedProgrammer** [comment]
This issue is also in CC1.79pre1.
It is just one line:
`loadfile( _sFile, _G )`
should be changed into:
`fnFile, e = loadfile( _sFile, _G )`

**Comment by apemanzilla** [comment]
Yeah, I initially found it in 1.79pr1 but reported it as 1.79pr0 because that's where the bug was introduced.

**Comment by apemanzilla** [comment]
@CrazedProgrammer Yup - I initially found it in 1.79pr1, but reported it as 1.79pr0 because it is present from that version onward.

**Comment by apemanzilla** [comment]
Just want to bump this in case @dan200 missed it.

**Comment by dan200** [comment]
I didn't miss it

**Comment by dan200** [comment]
Fixed for pr2
