### ISSUE TITLE
computercraft doesn't run on my turing machine

### ISSUE THREAD

**Issue by Lemmmy** [dan200/ComputerCraft#98]
please fix this this is very important to me

**Comment by apemanzilla** [comment]
It also doesn't seem to run on ENIAC which is a problem

**Comment by dan200** [comment]
Close this bug

**Comment by Lemmmy** [comment]
close it yourself you lazy slug

**Comment by Lemmmy** [comment]
i forgot you lived an hour away from me
please don't come to my house dan
