### ISSUE TITLE
Issue placing Malisis Doors with turtle.place()

### ISSUE THREAD

**Issue by Mowmaster** [dan200/ComputerCraft#99]
Single player game crashes in both the lastest 1.79 and the version before 1.78 when trying to place a Malisis camo gate, seems to dupe it (places it in the world and shows in the turtle inventory) when you load back into the game.

**Comment by dan200** [comment]
This report is not useful until you attach a crash log

**Comment by Mowmaster** [comment]
Whoops so sorry about that, [Pastebin](http://pastebin.com/HYvDk4g3)

**Comment by dan200** [comment]
Looks like the crash is coming from "Mallsis" code, it seems like they don't handle blocks being placed by fake players very well. Report the bug to them
